### ISSUE TITLE
Keptns Bridge: Provide links to deployed services

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1334] opened 2020-01-29 14:01 UTC
In the bridge when I explore in which stage which service is currently deployed I want to get a link to that service. That makes the bridge a great entry point to not only explore what is deployed in which stage and what the status is (green, failed, in progress) -but it also gives me a link to the URL of that service that I can directly open.

The dynatrace service does a great job when it is creating/updating the Dynatrace Dashboards by adding links to the public URLs of these services. Just something like this would be very valuable

**Comment by grabnerandi** [comment] 2020-01-29 14:02
Might be similar to this - https://github.com/keptn/keptn/issues/1278

**Comment by christian-kreuzberger-dtx** [comment] 2020-02-07 12:44
Closing this as a duplicate of #1278 (which is scheduled for 0.6.1 at the moment).

**Closed by christian-kreuzberger-dtx** 2020-02-07 12:44 UTC
Labels: area:bridge.2.0
