### ISSUE TITLE
ShipyardController panics with out of range error

### ISSUE THREAD

**Issue by warber** [keptn/keptn#4772] opened 2021-07-28 06:22 UTC
`ShipyardController` crashes from time to time with `runtime error: index out of range [0] with length 0`

**Environment**
* Keptn Version: 0.8.6

**Stack trace:**
```
Stacktrace: 
goroutine 6090 [running]:
github.com/keptn/keptn/shipyard-controller/handler/sequencehooks.(*SequenceStateMaterializedView).updateLastEventOfSequence(0xc00085ff10, 0x0, 0x0, 0x19532c0, 0xc0009b3110, 0x0, 0x0, 0xc000a30390, 0x24, 0xc000a303f0, ...)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/sequencehooks/sequencestate.go:198 +0xa25
github.com/keptn/keptn/shipyard-controller/handler/sequencehooks.(*SequenceStateMaterializedView).OnSubSequenceFinished(0xc00085ff10, 0x0, 0x0, 0x19532c0, 0xc0009b3110, 0x0, 0x0, 0xc000a30390, 0x24, 0xc000a303f0, ...)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/sequencehooks/sequencestate.go:105 +0xa5
github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).onSubSequenceFinished(0xc000160620, 0x0, 0x0, 0x19532c0, 0xc0009b3110, 0x0, 0x0, 0xc000a30390, 0x24, 0xc000a303f0, ...)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:112 +0xb5
github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).sendTaskSequenceFinishedEvent(0xc000160620, 0xc0005cfda8, 0xc00098193c, 0xa, 0xc0009818c0, 0x24, 0x89, 0x9)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:765 +0x405
github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).handleTriggeredEvent(0xc000160620, 0x0, 0x0, 0x19532c0, 0xc0005a3e30, 0x0, 0x0, 0xc0009818c0, 0x24, 0xc000981950, ...)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:256 +0xf76
github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).HandleIncomingEvent.func2(0xc000160620, 0xc00089b050, 0xc0007d09c0)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:155 +0x98
created by github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).HandleIncomingEvent
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:153 +0x327
```

**affected line of code:** https://github.com/keptn/keptn/blob/59693c309af0be1f12dadea5e27f0142f0607241/shipyard-controller/handler/sequencehooks/sequencestate.go#L198

**Comment by carpe-github** [comment] 2021-07-29 07:18
To reproduce the issue follow the steps below:

1. Create git personal access token with the permissions like below:
![image](https://user-images.githubusercontent.com/63784298/127446583-05559240-3d3f-4860-9930-3b0385075df9.png)
2. Set the value of access token in Keptn
![image](https://user-images.githubusercontent.com/63784298/127448382-c72e0886-428d-4d06-a507-f6812a4573bb.png)
3. trigger an evaluation via API
curl -X POST "https://lyn50682.cloudautomation.dev.dynatracelabs.com/api/controlPlane/v1/project/dynatrace/stage/quality-gate/service/items/evaluation" -H "accept: application/json" -H "x-token: XXXXXXXXXXXXXX" -H "Content-Type: application/json" -d "{ \"timeframe\": \"5m\"}"

The response should be like this:
`<html>
<head><title>502 Bad Gateway</title><script type="text/javascript" src="/ruxitagentjs_ICA2EQSVfghjqru_10224210726152847.js" data-dtconfig="rid=RID_-1365579993|rpid=-2024366259|domain=dynatracelabs.com|reportUrl=/rb_bf29941wkd|agentId=a445754af9f0ada8|rcdec=1209600000|msl=153600|rdnt=1|uxrgce=1|bp=3|srmcrv=10|srxcss=1|mel=100000|srmrc=1|dpvc=1|md=mdcc1=btenantId,mdcc2=a[name='dtUser']@content|ssv=3|dtVersion=10224210726152847|srmcrl=1|app=3a643e3627bf4e5e|featureHash=ICA2EQSVfghjqru|vcv=2|srvr=%2F%23settings%2Fkubernetesmonitoring|cuc=4rerpdvp|srxicss=1|srms=1,1,,,,2,1,0,0%2Ftextarea%2Cinput%2Cselect%2Coption;0%2Fdatalist;0%2Fform%20button;0%2F%5Bdata-dtrum-input%5D;0%2F.data-dtrum-input;1%2F%5Edata%28%28%5C-.%2B%24%29%7C%24%29|srsdom=1|lastModification=1627540877012|tp=500,50,0,1|uxdcw=1500|vs=2|agentUri=/ruxitagentjs_ICA2EQSVfghjqru_10224210726152847.js"></script></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.19.4</center>
</body>
</html>






`
4. The stacktrace of the crash  can be fetched from Kubernetes logs (shipyard-controller shipyard-controller-)

`time="2021-07-29T06:52:09Z" level=error msg="could not retrieve shipyard: Could not retrieve shipyard.yaml for project dynatrace: {\"code\":500,\"message\":\"Could not check out branch\"}\n"
panic: runtime error: index out of range [0] with length 0
goroutine 392204 [running]:
github.com/keptn/keptn/shipyard-controller/handler/sequencehooks.(*SequenceStateMaterializedView).updateLastEventOfSequence(0xc000826070, 0x0, 0x0, 0x19532c0, 0xc0007bc2a0, 0x0, 0x0, 0xc0002ffe00, 0x24, 0xc0002fff50, ...)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/sequencehooks/sequencestate.go:198 +0xa25
github.com/keptn/keptn/shipyard-controller/handler/sequencehooks.(*SequenceStateMaterializedView).OnSubSequenceFinished(0xc000826070, 0x0, 0x0, 0x19532c0, 0xc0007bc2a0, 0x0, 0x0, 0xc0002ffe00, 0x24, 0xc0002fff50, ...)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/sequencehooks/sequencestate.go:105 +0xa5
github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).onSubSequenceFinished(0xc000160620, 0x0, 0x0, 0x19532c0, 0xc0007bc2a0, 0x0, 0x0, 0xc0002ffe00, 0x24, 0xc0002fff50, ...)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:112 +0xb5
github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).sendTaskSequenceFinishedEvent(0xc000160620, 0xc000b11da8, 0xc0002ff72c, 0xa, 0xc000811fb0, 0x24, 0x89, 0x9)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:765 +0x405
github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).handleTriggeredEvent(0xc000160620, 0x0, 0x0, 0x19532c0, 0xc0009f19e0, 0x0, 0x0, 0xc000811fb0, 0x24, 0xc0002ff770, ...)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:256 +0xf76
github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).HandleIncomingEvent.func2(0xc000160620, 0xc000721dd0, 0xc0006d6840)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:155 +0x98
created by github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).HandleIncomingEvent
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:153 +0x327
goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f393bbfccb8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000908018, 0x72, 0x0, 0x0, 0x1b5ce5f)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000908000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc000908000, 0x255746151b07ed02, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc0006482e8, 0x61025019, 0xc00088d9d0, 0x4cda86)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0006482e8, 0xc00088da20, 0x18, 0xc000000180, 0x6ed73b)
	/usr/local/go/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc000906000, 0x1eda750, 0xc0006482e8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2981 +0x285
net/http.(*Server).ListenAndServe(0xc000906000, 0xc000906000, 0xc00089fbd0)
	/usr/local/go/src/net/http/server.go:2910 +0xba
net/http.ListenAndServe(...)
	/usr/local/go/src/net/http/server.go:3164
github.com/gin-gonic/gin.(*Engine).Run(0xc0005cfd40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/gin.go:336 +0x1ba
main.main()
	/go/src/github.com/keptn/keptn/shipyard-controller/main.go:152 +0x1187
goroutine 18 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x299fe40)
	/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
	/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0xdf
goroutine 9 [select]:
`

**Comment by bacherfl** [comment] 2021-08-09 09:00
I just investigated this issue - this problem has been fixed in the meantime since a check for the length of the concerning array has been added: https://github.com/keptn/keptn/blob/942bf66e16aa6db2377b1aa358e18d7da37c148d/shipyard-controller/handler/sequencehooks/sequencestate.go#L214

**Closed by bacherfl** 2021-08-09 09:00 UTC
Labels: type:bug, area:core
