### ISSUE TITLE
Explain webhook started / finished as async or sync

### ISSUE THREAD

**Issue by chapaith** [keptn/keptn#8831] opened 2022-09-09 08:44 UTC
Improve / add to the wording of the webhok service screen so tell users that the model is sync or async.

Describe the solution you'd like
Adjust the wording on the webhook bridge screen to explain started and finished events more clearly to the user.

Sending started and finished from webhook service is an "async" model. The Keptn task immediately returns. In contrast, delegating the finished event to the receiving service will wait until the receiver is done. Thus it is a synchronous model and will "block.

Async is easier at first to implement as it needs no changes to the receiving side, but the task timing does not include the processing time of the receiving system. Sync allows users to send data from the system back to Keptn and gives accurate timings, but requires modifications.

Users usually start with the async model as it is easiest to implement.

**Comment by thisthat** [comment] 2022-09-10 09:40
Duplicate of #8652

**Closed by thisthat** 2022-09-10 09:40 UTC
Labels: doc
