### ISSUE TITLE
Facing issue "Disk quota exceeded" while adding arm64 job in travis

### ISSUE THREAD

**Issue by odidev** [keptn/keptn#2284] opened 2020-09-03 12:54 UTC
Hi,

I am checking on adding arm64 jobs in travis.. 

I have successfully added the arm64 support for the unit testing stage in travis.

I was also trying to build the docker image for arm64 but it was failing with below error:

```
Error processing tar file(exit status 1): write /go/pkg/mod/google.golang.org/api@v0.6.0/vision/v1p1beta1/vision-gen.go: disk quota exceeded
```

Travis Link : https://travis-ci.com/github/odidev/keptn/builds/182568915

I want to know whether you are planning on adding arm64 support and can i get any suggestions on how we can resolve the above issue?

**Comment by agrimmer** [comment] 2020-09-04 09:26
Hi @odidev,
thanks for bringing up this issue!
We have not yet looked into providing ARM support for Keptn. 
But we would be interested in your use case. Can you please your use case? Are you on EKS?
Thanks, Andreas

**Comment by christian-kreuzberger-dtx** [comment] 2020-09-07 12:31
Hi,

according to [travis ci docs](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system) there should be roughly 18 GB of disk space available for arm64 builds.

Looking at your travis ci log output, the problem seems to occur when building docker images. It might be that the 18 GB is not enough (I believe our builds have 50 GB available), but one would have to try this out locally to figure out how much space is needed.

One way to temporarily overcome this issue is splitting up the build jobs in multiple jobs.

**Comment by rhenwood-arm** [comment] 2020-09-09 20:25
@agrimmer  - I'm working with @odidev on this. We do not have a specific use case but are working to support various cloud-native developer scenarios, including those using Keptn.

**Comment by christian-kreuzberger-dtx** [comment] 2020-09-14 09:38
After some googling, I found that this is a known issue with travis and arm64 builds, mainly caused by the fact that there just isn't enough disk space available :( - see https://travis-ci.community/t/disk-quota-exceeded/5507/12

If my above recommendation about splitting the jobs into multiple builds is no option right now, you can also try to use a VM locally (if you have enough memory and storage) and start building the images there.

Or you can try to spool up an [ARM64 VM on AWS](https://aws.amazon.com/blogs/aws/new-ec2-instances-a1-powered-by-arm-based-aws-graviton-processors/).

Regarding use-cases, the following two comes to my mind:

* Running Keptn on Raspberry PI with K3s (requires Docker Images to be compatible for ARM64)
* Developing and building Keptn on a Raspberry PI (though to be honest with you, that's more of a solution to a problem that does not exist)

**Comment by christian-kreuzberger-dtx** [comment] 2020-09-16 06:10
Good news: Travis-Ci.com (not .org) is going to have better arm64 support in the near future: https://blog.travis-ci.com/2020-09-11-arm-on-aws

**Comment by johannes-b** [comment] 2020-11-16 07:32
Keptn has been successfully migrated to `travis-ci.com` (https://github.com/keptn/keptn/issues/2356). 

This should help to work on this task since Travis-ci.com provides better support from arm64.

**Comment by christian-kreuzberger-dtx** [comment] 2021-01-15 10:32
We have moved to github actions, as travis-ci has effectively killed OpenSource support.

@odidev  @rhenwood-arm can you verify if you still have this issue with GH actions? If not, I'd like to close this.

**Comment by odidev** [comment] 2021-01-15 12:11
@christian-kreuzberger-dtx thanks for your support and time for resolving this issue. 
I think we can close this issue.

**Closed** 2021-01-15 14:53 UTC
