### ISSUE TITLE
signal SIGSEGV: segmentation violation on helm-service

### ISSUE THREAD

**Issue by braghettos** [keptn/keptn#7061] opened 2022-03-03 18:11 UTC
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): 0.13.1
* Kubernetes Cloud Provider (e.g., GKE, AKS): OpenShift
* Kubernetes version (`kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+b93fd35", GitCommit:"3a0f2c90b43e6cffd07f57b5b78dd9f083e47ee2", GitTreeState:"clean", BuildDate:"2022-02-11T05:26:59Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

Once helm-service is installed in a multicluster setup, after releasing the chart it always restarts because of this error:

> {"timestamp":"2022-03-03T15:18:25.775564696Z","logLevel":"INFO","message":"Starting deployment for service test-20220303-5-svc in stage svil of project test-20220303-5"}
> {"timestamp":"2022-03-03T15:18:25.784516125Z","logLevel":"INFO","message":"Updating values for service test-20220303-5-svc in stage svil of project test-20220303-5"}
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x25a83c5]
> goroutine 2495 [running]:
> github.com/keptn/keptn/helm-service/pkg/configurationchanger.(*ValuesManipulator).Manipulate(0xc000506348, 0x0, 0x13, 0x0)
>     /go/src/github.com/keptn/keptn/helm-service/pkg/configurationchanger/values_manipulator.go:25 +0xc5
> github.com/keptn/keptn/helm-service/pkg/configurationchanger.(*ConfigurationChanger).UpdateLoadedChart(0xc00023cc68, 0x0, 0xc000416f80, 0xf, 0xc000416f7c, 0x4, 0xc000058990, 0x13, 0x0, 0x0, ...)
>     /go/src/github.com/keptn/keptn/helm-service/pkg/configurationchanger/configuration_changer.go:34 +0xca
> github.com/keptn/keptn/helm-service/controller.(*DeploymentHandler).HandleEvent(0xc000621600, 0x2da30c0, 0xc000264d20, 0xc0000dc000, 0x173, 0x180, 0x0, 0x0)
>     /go/src/github.com/keptn/keptn/helm-service/controller/deployment_handler.go:67 +0xdc5
> main.gracefulMiddleware(0x2d786e0, 0xc0001fa000, 0x2da30c0, 0xc000264d20, 0xc0000dc000, 0x173, 0x180, 0x0, 0x0, 0x2d97448, ...)
>     /go/src/github.com/keptn/keptn/helm-service/main.go:243 +0xd1
> created by main.gotEvent
>     /go/src/github.com/keptn/keptn/helm-service/main.go:102 +0xfdc
> goroutine 1 [select, 25 minutes]:
> github.com/cloudevents/sdk-go/v2/protocol/http.(*Protocol).OpenInbound(0xc00011ed00, 0x2d78440, 0xc0001fe2c0, 0x0, 0x0)
>     /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/protocol/http/protocol_lifecycle.go:57 +0x365
> github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver(0xc00011f040, 0x2d78440, 0xc0001fe280, 0x2786aa0, 0x2b80a08, 0x0, 0x0)
>     /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/client/client.go:265 +0x458
> main._main(0xc000118200, 0x0, 0x0, 0x1f90, 0x264bf56, 0x1, 0xc00005401a, 0x4, 0xc000000180)
>     /go/src/github.com/keptn/keptn/helm-service/main.go:200 +0x388
> main.main()
>     /go/src/github.com/keptn/keptn/helm-service/main.go:62 +0x199
> goroutine 19 [chan receive]:
> k8s.io/klog/v2.(*loggingT).flushDaemon(0x3bebb00)
>     /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1169 +0x8b
> created by k8s.io/klog/v2.init.0
>     /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:420 +0xdf

After the restard, the helm-service doesn't handle anymore other sequences.

**To Reproduce**

1. Install Keptn 0.13.1 via helm chart 
2. Install helm-service 0.13.1 via helm chart
3. Trigger sequence delivery

**Expected behavior**

helm-service correctly releasing helm-charts

**Current behavior**

After the first release, the pod restarts and doesn't release any more charts.

**Screenshots**

**Additional context**

**Comment by odubajDT** [comment] 2022-03-04 12:35
Hi @braghettos, can you please provide us some more information about what app are you trying to deliver? Or what resources have you added to the git repository before triggering the delivery (shipyard, helm charts,...)? A detailed step-by-step guide how to reproduce the problem with the resources linked will be awesome :)

Thank you in advance!

**Comment by braghettos** [comment] 2022-03-04 13:26
Hi @odubajDT , this is the git upstream repo where you can find everything: https://github.com/krateoplatformops/test-20220303-5-keptn

Basically what we are trying to do is to trigger the sequence with the following payload:

```
{
  "data": {
    "configurationChange": {
      "values": {
        "image": "image-registry.openshift-image-registry.svc:5000/cloudbees/test-20220303-5:latest"
      }
    },
    "deployment": {
      "deploymentURIsLocal": null,
      "deploymentstrategy": ""
    },
    "project": "test-20220303-5",
    "service": "test-20220303-5-svc",
    "stage": "svil"
  },
  "id": "45475a6a-9827-47b9-a658-8cee8a47a6c2",
  "shkeptncontext": "99ad9f95-848f-4c59-a781-31f78755658e",
  "shkeptnspecversion": "0.2.4",
  "source": "https://github.com/keptn/keptn/cli#configuration-change",
  "specversion": "1.0",
  "time": "2022-03-04T11:38:01.860Z",
  "type": "sh.keptn.event.svil.delivery-direct.triggered"
}
```

This is the log we found in the killed pod:

```
{"timestamp":"2022-03-04T13:12:10.672707506Z","logLevel":"INFO","message":"Starting deployment for service test-20220303-5-svc in stage svil of project test-20220303-5"}
{"timestamp":"2022-03-04T13:12:10.691889171Z","logLevel":"INFO","message":"Updating values for service test-20220303-5-svc in stage svil of project test-20220303-5"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x25a83c5]
goroutine 9068 [running]:
github.com/keptn/keptn/helm-service/pkg/configurationchanger.(*ValuesManipulator).Manipulate(0xc000010280, 0x0, 0x13, 0x0)
    /go/src/github.com/keptn/keptn/helm-service/pkg/configurationchanger/values_manipulator.go:25 +0xc5
github.com/keptn/keptn/helm-service/pkg/configurationchanger.(*ConfigurationChanger).UpdateLoadedChart(0xc00020ac68, 0x0, 0xc000558bc0, 0xf, 0xc000558ba8, 0x4, 0xc0006c8480, 0x13, 0x0, 0x0, ...)
    /go/src/github.com/keptn/keptn/helm-service/pkg/configurationchanger/configuration_changer.go:34 +0xca
github.com/keptn/keptn/helm-service/controller.(*DeploymentHandler).HandleEvent(0xc00007f700, 0x2da30c0, 0xc0000209a0, 0xc000024000, 0x198, 0x1a0, 0x0, 0x0)
    /go/src/github.com/keptn/keptn/helm-service/controller/deployment_handler.go:67 +0xdc5
main.gracefulMiddleware(0x2d786e0, 0xc00001e020, 0x2da30c0, 0xc0000209a0, 0xc000024000, 0x198, 0x1a0, 0x0, 0x0, 0x2d97448, ...)
    /go/src/github.com/keptn/keptn/helm-service/main.go:243 +0xd1
created by main.gotEvent
    /go/src/github.com/keptn/keptn/helm-service/main.go:102 +0xfdc
goroutine 1 [select, 94 minutes]:
github.com/cloudevents/sdk-go/v2/protocol/http.(*Protocol).OpenInbound(0xc00056c270, 0x2d78440, 0xc00079a2c0, 0x0, 0x0)
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/protocol/http/protocol_lifecycle.go:57 +0x365
github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver(0xc00056c410, 0x2d78440, 0xc00079a280, 0x2786aa0, 0x2b80a08, 0x0, 0x0)
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/client/client.go:265 +0x458
main._main(0xc00004e220, 0x0, 0x0, 0x1f90, 0x264bf56, 0x1, 0xc00005401a, 0x4, 0xc000000180)
    /go/src/github.com/keptn/keptn/helm-service/main.go:200 +0x388
main.main()
    /go/src/github.com/keptn/keptn/helm-service/main.go:62 +0x199
goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x3bebb00)
    /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
    /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:420 +0xdf
goroutine 40 [syscall, 94 minutes]:
os/signal.signal_recv(0x2b7ea70)
    /usr/local/go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
    /usr/local/go/src/os/signal/signal.go:151 +0x45
goroutine 41 [chan receive, 94 minutes]:
main.getGracefulContext.func1(0xc000554ba0, 0xc000558000, 0xc000378ad0)
    /go/src/github.com/keptn/keptn/helm-service/main.go:229 +0x38
created by main.getGracefulContext
    /go/src/github.com/keptn/keptn/helm-service/main.go:228 +0x18f
goroutine 42 [select]:
github.com/cloudevents/sdk-go/v2/protocol/http.(*Protocol).Respond(0xc00056c270, 0x2d78440, 0xc00079a2c0, 0xc000378b10, 0x2d78718, 0xc0006d01e0, 0xc0002a7230, 0xc000558030)
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/protocol/http/protocol.go:267 +0xd8
github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver.func2(0xc000558030, 0xc00056c410, 0xc000378b10)
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/client/client.go:236 +0x302
created by github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/client/client.go:228 +0x3a5
goroutine 43 [select, 94 minutes]:
github.com/cloudevents/sdk-go/v2/protocol/http.(*Protocol).Respond(0xc00056c270, 0x2d78440, 0xc00079a2c0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/protocol/http/protocol.go:267 +0xd8
github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver.func2(0xc000558030, 0xc00056c410, 0xc000378b10)
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/client/client.go:236 +0x302
created by github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/client/client.go:228 +0x3a5
goroutine 44 [select, 94 minutes]:
github.com/cloudevents/sdk-go/v2/protocol/http.(*Protocol).Respond(0xc00056c270, 0x2d78440, 0xc00079a2c0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/protocol/http/protocol.go:267 +0xd8
github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver.func2(0xc000558030, 0xc00056c410, 0xc000378b10)
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/client/client.go:236 +0x302
created by github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/client/client.go:228 +0x3a5
goroutine 45 [select, 94 minutes]:
github.com/cloudevents/sdk-go/v2/protocol/http.(*Protocol).Respond(0xc00056c270, 0x2d78440, 0xc00079a2c0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/protocol/http/protocol.go:267 +0xd8
github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver.func2(0xc000558030, 0xc00056c410, 0xc000378b10)
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/client/client.go:236 +0x302
created by github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/client/client.go:228 +0x3a5
goroutine 46 [IO wait]:
internal/poll.runtime_pollWait(0x7f7fee6c3eb8, 0x72, 0x0)
    /usr/local/go/src/runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc00079d498, 0x72, 0x0, 0x0, 0x2a94895)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00079d480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc00079d480, 0xd68845bfb0d9d2e4, 0x0, 0x0)
    /usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc00000e078, 0x6222102a, 0xc00015de10, 0xdb0b86)
    /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00000e078, 0xc00015de60, 0x18, 0xc000552a80, 0x105af9b)
    /usr/local/go/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc00031a000, 0x2d72f90, 0xc00000e078, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2962 +0x285
github.com/cloudevents/sdk-go/v2/protocol/http.(*Protocol).OpenInbound.func2(0xc0006182a0, 0xc00056c270, 0x2d72f90, 0xc00000e078)
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/protocol/http/protocol_lifecycle.go:53 +0x46
created by github.com/cloudevents/sdk-go/v2/protocol/http.(*Protocol).OpenInbound
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/protocol/http/protocol_lifecycle.go:52 +0x2d1
goroutine 9054 [IO wait]:
internal/poll.runtime_pollWait(0x7f7fee6c3dd0, 0x72, 0xffffffffffffffff)
    /usr/local/go/src/runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc0004a0e98, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0004a0e80, 0xc0001fd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0004a0e80, 0xc0001fd000, 0x1000, 0x1000, 0xc0001f6e88, 0xc0001f6d18, 0x2)
    /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0005b01e8, 0xc0001fd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc0005c58c0, 0xc0001fd000, 0x1000, 0x1000, 0xc0001f6dc4, 0x2, 0x2)
    /usr/local/go/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc000554720)
    /usr/local/go/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc000554720, 0x1, 0x0, 0x1, 0x1, 0x1, 0x0)
    /usr/local/go/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc0005c58c0)
    /usr/local/go/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:1743 +0xc77
goroutine 9065 [IO wait]:
internal/poll.runtime_pollWait(0x7f7fee6c3b18, 0x72, 0xffffffffffffffff)
    /usr/local/go/src/runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc000796798, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000796780, 0xc00016d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000796780, 0xc00016d000, 0x1000, 0x1000, 0x0, 0x7f7fee6c3b20, 0x0)
    /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000010110, 0xc00016d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:183 +0x91
net/http.(*connReader).Read(0xc0002a7170, 0xc00016d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:780 +0x1b9
bufio.(*Reader).fill(0xc000499c20)
    /usr/local/go/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc000499c20, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:139 +0x4f
net/http.(*conn).readRequest(0xc000419ea0, 0x2d78440, 0xc00007f400, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:963 +0xec5
net/http.(*conn).serve(0xc000419ea0, 0x2d784e8, 0xc00007f400)
    /usr/local/go/src/net/http/server.go:1859 +0x705
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2994 +0x39b
goroutine 9075 [select]:
net/http.(*persistConn).writeLoop(0xc00048f0e0)
    /usr/local/go/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:1744 +0xc9c
goroutine 9074 [IO wait]:
internal/poll.runtime_pollWait(0x7f7fee6c3c00, 0x72, 0xffffffffffffffff)
    /usr/local/go/src/runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc0004a0f18, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0004a0f00, 0xc00026f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0004a0f00, 0xc00026f000, 0x1000, 0x1000, 0xd5699c, 0xc000159c38, 0xd82260)
    /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0005b0208, 0xc00026f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc00048f0e0, 0xc00026f000, 0x1000, 0x1000, 0xc0000a55c0, 0xc000159d40, 0xd21eb5)
    /usr/local/go/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc0005547e0)
    /usr/local/go/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc0005547e0, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
    /usr/local/go/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc00048f0e0)
    /usr/local/go/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:1743 +0xc77
goroutine 9055 [select]:
net/http.(*persistConn).writeLoop(0xc0005c58c0)
    /usr/local/go/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:1744 +0xc9c
```

Helm-service is at version 0.13.1.

**Comment by odubajDT** [comment] 2022-03-04 13:43
Just from looking at the docker image name, I assume that the image registry should not contain a port (:5000), as when the image is parsed by the helm-service, it tries to handle everything after ":" as a tag, which also contains ":". That can lead to undefined behaviour of helm-service. There should definitely be no SIGSEGV after adding such image and it will be fixed, but at least it may help you deploying your application for now.

Hope this helps.

Note: please keep in mind, that no proper investigation was made before this suggestion and it will be properly investigated in the next week

**Comment by odubajDT** [comment] 2022-03-07 08:33
It seems that the problem is already fixed in the current master branch, as I am unable to reproduce it with the latest nightly build.

**Comment by odubajDT** [comment] 2022-03-08 07:25
Closing this issue, as it is fixed in the current master branch and when adding the image in the correct format, no problems are present in version 0.13.1. Please feel free to reopen this ticket, if you face any problems or you need further assistance with installing newer version.

**Comment by braghettos** [comment] 2022-03-08 12:13
I'm sorry but we are still experiencing this issue even if we fixed the format of the image. This is the payload:

{
  "data": {
    "configurationChange": {
      "values": {
        "image": "nexus-registry.apps.ocp4-test.it/krateo-20220308:latest"
      }
    },
    "deployment": {
      "deploymentURIsLocal": null,
      "deploymentstrategy": "user_managed"
    },
    "message": "",
    "project": "krateo-20220308",
    "result": "",
    "service": "krateo-20220308",
    "stage": "svil",
    "status": ""
  },
  "gitcommitid": "dd389fd608ba09ce490f3c05bcd2f7e296da8c76",
  "id": "2983a919-c8c4-4862-b942-8e3199ecf0d5",
  "shkeptncontext": "d5e0c9d6-2395-4ae5-9dbe-53dcec076f58",
  "shkeptnspecversion": "0.2.4",
  "source": "shipyard-controller",
  "specversion": "1.0",
  "time": "2022-03-08T10:44:36.026Z",
  "type": "sh.keptn.event.deployment.triggered"
}

**Comment by braghettos** [comment] 2022-03-08 12:22
This is the pod log:

{"timestamp":"2022-03-08T10:44:42.143394395Z","logLevel":"INFO","message":"Starting deployment for service krateo-20220308 in stage svil of project krateo-20220308"}
{"timestamp":"2022-03-08T10:44:42.197114575Z","logLevel":"INFO","message":"Updating values for service krateo-20220308 in stage svil of project krateo-20220308"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x25a83c5]
goroutine 1284 [running]:
github.com/keptn/keptn/helm-service/pkg/configurationchanger.(*ValuesManipulator).Manipulate(0xc0005a6070, 0x0, 0xf, 0x0)
    /go/src/github.com/keptn/keptn/helm-service/pkg/configurationchanger/values_manipulator.go:25 +0xc5
github.com/keptn/keptn/helm-service/pkg/configurationchanger.(*ConfigurationChanger).UpdateLoadedChart(0xc000232c68, 0x0, 0xc0006a2ad0, 0xf, 0xc0006a2ab8, 0x4, 0xc0006a2ae0, 0xf, 0x0, 0x0, ...)
    /go/src/github.com/keptn/keptn/helm-service/pkg/configurationchanger/configuration_changer.go:34 +0xca
github.com/keptn/keptn/helm-service/controller.(*DeploymentHandler).HandleEvent(0xc000497500, 0x2da30c0, 0xc0002d2a80, 0xc0002e2000, 0x181, 0x1a0, 0x0, 0x0)
    /go/src/github.com/keptn/keptn/helm-service/controller/deployment_handler.go:67 +0xdc5
main.gracefulMiddleware(0x2d786e0, 0xc000830020, 0x2da30c0, 0xc0002d2a80, 0xc0002e2000, 0x181, 0x1a0, 0x0, 0x0, 0x2d97448, ...)
    /go/src/github.com/keptn/keptn/helm-service/main.go:243 +0xd1
created by main.gotEvent
    /go/src/github.com/keptn/keptn/helm-service/main.go:102 +0xfdc
goroutine 1 [select, 12 minutes]:
github.com/cloudevents/sdk-go/v2/protocol/http.(*Protocol).OpenInbound(0xc000145a00, 0x2d78440, 0xc000496e00, 0x0, 0x0)
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/protocol/http/protocol_lifecycle.go:57 +0x365
github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver(0xc000145ad0, 0x2d78440, 0xc000496dc0, 0x2786aa0, 0x2b80a08, 0x0, 0x0)
    /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/client/client.go:265 +0x458
main._main(0xc00004e220, 0x0, 0x0, 0x1f90, 0x264bf56, 0x1, 0xc00005401a, 0x5, 0xc000000180)
    /go/src/github.com/keptn/keptn/helm-service/main.go:200 +0x388
main.main()
    /go/src/github.com/keptn/keptn/helm-service/main.go:62 +0x199
goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x3bebb00)
    /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
    /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:420 +0xdf
goroutine 13 [chan receive, 12 minutes]:
main.getGracefulContext.

**Comment by odubajDT** [comment] 2022-03-08 12:59
There was a new version released today (0.13.2), can you please check if it happens also on this version ?

**Comment by braghettos** [comment] 2022-03-08 13:29
Can I upgrade just the helm-service?

**Comment by odubajDT** [comment] 2022-03-08 13:32
yes, that can say us something

**Comment by odubajDT** [comment] 2022-03-08 13:36
`helm upgrade helm-service -n keptn --reuse-values ./helm-service-0.13.2.tgz`

https://github.com/keptn/keptn/releases/tag/0.13.2

**Comment by braghettos** [comment] 2022-03-08 15:44
Same error. Which info do you need for troubleshooting?

**Comment by braghettos** [comment] 2022-03-08 16:36
@odubajDT could we schedule a call to investigate together my environment?

**Comment by odubajDT** [comment] 2022-03-09 06:19
Sure, when do you have time?

Just a question regarding the Keptn, are you using `resource-service` or `configuration-service` ? If `resource-service`, have you used `resource-service` together with `gitcommitid` ? From what I see in the `triggered` event I assume yes. If yes, this is a known issue on our side, let me explain.

When uploading resources to the git repository, helm-charts are uploaded as a tarball and extracted afterwards. When triggering a delivery with a specific `gitcommitid`, we are currently unable to compress the extracted helm-charts and provide them to `helm-service`. That's why you are receiving SIGSEGV in `helm-service`, as `resource-service` was unable to provide the helm-charts to it.

**Comment by odubajDT** [comment] 2022-03-09 06:47
Can you please use this image and see if everything works properly with it ?

https://hub.docker.com/layers/196307157/odubajdt/keptndev_helm-service/0.13.2-dirty/images/sha256-eecff9a4d25c58aca3e2e09efa92e720018d0225499866414467509cb6e1d43a?context=repo

Please be aware, this is not an official image released by Keptn team, just a developer image to override the current problems

**Comment by braghettos** [comment] 2022-03-09 08:01
@odubajDT could you write to me on the Keptn Slack so we can arrange the meeting at 10:00 am? I am Diego Braga

**Comment by odubajDT** [comment] 2022-03-09 08:57
I do not have time now, can we arrange a zoom meeting at around 12:30 UTC? Actually have you managed to use the provided testing image ?

**Comment by braghettos** [comment] 2022-03-09 09:01
Perfect at 12:30 UTC. I tested the provided image but I got the same issue.

**Comment by odubajDT** [comment] 2022-03-09 09:09
If you don't mind, I just got cancelled one of my meetings, do you have time now ?

**Comment by odubajDT** [comment] 2022-03-09 09:10
https://dynatrace.zoom.us/j/91303498843?pwd=eTEydWRNSmdEWVkxcHpzRDJKRTRVUT09

**Comment by odubajDT** [comment] 2022-03-09 10:12
Hi, I actually found a problem causing the SIGSEGV, can you please assist us with testing it?

Regarding to our call, can you upload the resource with the invalid name (test-0.1.0, or something like that) and install this image?

https://hub.docker.com/layers/odubajdt/keptndev_helm-service/0.13.2-dirty/images/sha256-024ed3e2e9b0e4eea26fadd0f33b506c223f251ead643309e86868b808d60fb2?context=explore

With this image and the invalid helm-charts name, you should not get a SIGSEGV signal, but a error message. Can you please test it on your environment ?

Thank you!

**Comment by odubajDT** [comment] 2022-03-09 10:28
Yes, that is expected, thank you for testing!

**Closed** 2022-03-10 07:09 UTC
Labels: type:bug
