### ISSUE TITLE
keptn cli doesn't create projects or services

### ISSUE THREAD

**Issue by maurosala** [keptn/keptn#6325] opened 2021-12-09 13:52 UTC
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**
* Client OS (e.g., Linux, macOS, Windows): macos
* Keptn Version (`keptn version`): 0.11.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): EKS
* Kubernetes version (`kubectl version`): v1.21.2-eks-06eac09
--

<br class="Apple-interchange-newline">

**Affected Component**

* [ ] Approval
* [X] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

**To Reproduce**

1. Create a shipyard file
```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-krateo"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "direct"
            - name: "test"
              properties:
                teststrategy: "functional"
            - name: "evaluation"
            - name: "release"
        - name: "delivery-direct"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "direct"
            - name: "release"

    - name: "staging"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "dev.delivery.finished"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "blue_green_service"
            - name: "test"
              properties:
                teststrategy: "performance"
            - name: "evaluation"
            - name: "release"
        - name: "rollback"
          triggeredOn:
            - event: "staging.delivery.finished"
              selector:
                match:
                  result: "fail"
          tasks:
            - name: "rollback"
        - name: "delivery-direct"
          triggeredOn:
            - event: "dev.delivery-direct.finished"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "direct"
            - name: "release"

    - name: "production"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "staging.delivery.finished"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "blue_green_service"
            - name: "release"
        - name: "rollback"
          triggeredOn:
            - event: "production.delivery.finished"
              selector:
                match:
                  result: "fail"
          tasks:
            - name: "rollback"
        - name: "delivery-direct"
          triggeredOn:
            - event: "staging.delivery-direct.finished"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "direct"
            - name: "release"

        - name: "remediation"
          triggeredOn:
            - event: "production.remediation.finished"
              selector:
                match:
                  evaluation.result: "fail"
          tasks:
            - name: "get-action"
            - name: "action"
            - name: "evaluation"
              triggeredAfter: "2m"
              properties:
                timeframe: "2m"

```
2. Run this command
`keptn create project krateo --shipyard=./shipyard.yaml`
3. This is the output
```
WARNING: Creating a project without Git upstream repository is not recommended. 
You can configure a Git upstream repository using: 

keptn update project PROJECTNAME --git-user=GIT_USER --git-token=GIT_TOKEN --git-remote-url=GIT_REMOTE_URL

Starting to create project
Project created successfully
```
4. Project is not created.
If you upload the shipyard file from the WebUI it works correctly.
No error logs on configuration-service or shipyard-controller.
5. After the project is successfully created from the WebUI, run this command
```
keptn create service demo --project=krateo
```
6. This is the output
```
Starting to create service
Create service was unsuccessful
Error: Create service was unsuccessful. invalid character 'p' after top-level value
-----DETAILS-----404 page not found
```

**Comment by oleg-nenashev** [comment] 2021-12-13 07:06
FWIW it might be similar to https://github.com/keptn/keptn.github.io/issues/984 . In this issue a space inside the SLI expression led to a broken Prometheus configuration file: https://github.com/keptn/examples/blob/4dcf77e307e62b07c9c4bd16572650803cd38c4f/quickstart/demo/slo.yaml#L28-L32 . Since the YAML generation in Keptn is unified, I suspect a systemic issue under the hood

@maurosala Any chance you could extract the configuration file from the POD

**Comment by maurosala** [comment] 2021-12-13 07:47
Hi @oleg-nenashev, I have found the problem.
Our keptn bridge is behind cloudflare proxy.
There are two possibilities in cloudflare (as you can see here)
![image](https://user-images.githubusercontent.com/10496197/145772124-dda34f43-26d2-4bce-b240-c532cab7f780.png)
If I enable the proxy keptn client does not work, but if I disable it and expose the bridge directly all seems to work.

**Comment by oleg-nenashev** [comment] 2021-12-13 07:52
Thanks for the update! This error message is weird anyway:

```
Starting to create service
Create service was unsuccessful
Error: Create service was unsuccessful. invalid character 'p' after top-level value
-----DETAILS-----404 page not found
```

**Comment by thisthat** [comment] 2021-12-14 07:40
Hi @maurosala, I am glad that you found out about the root cause of the problem. I will close this issue and open a new ticket to provide the possibility to connect to a Keptn installation via a proxy server.

**Closed by thisthat** 2021-12-14 07:40 UTC
Labels: type:bug
