### ISSUE TITLE
Services are temporarily unavailable 

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#392] opened 2019-05-24 11:54 UTC
Services like _control_ or the _keptn bridge_ are temporarily unavailable.
For example, in the CLI we get an error message like
`Post https://control.keptn.1xx.xxx.xx.xx.xip.io/service: dial tcp: lookup control.keptn.1xx.xxx.xx.xx.xip.io: no such host`.

Investigate the reason for this unavailability.

**Comment by agrimmer** [comment] 2019-05-25 06:38
Further background: When calling the swagger-api, we get a `DNS_PROBE_FINISHED_NXDOMAIN` error.

**Comment by jetzlstorfer** [comment] 2019-06-12 13:23
The root cause of this issue is that during peak hours, xip.io is unfortunately not very reliable. Therefore, the host can not be resolved and the CLI will return this error.

**Comment by dirkwall** [comment] 2019-06-19 07:09
Closing, as this issue is related to xip.io availability.

**Closed by dirkwall** 2019-06-19 07:09 UTC
Labels: area:core, area:infra, type:bug
