### ISSUE TITLE
SLi evaluation fails when using keptn for quality gates only

### ISSUE THREAD

**Issue by cjmckenna** [keptn/keptn#2428] opened 2020-09-28 18:07 UTC
**Environment**
any supported platform for keptn.  I made it happen in EKS, GKE and minikube

* Client OS OSX
* Keptn Version (`keptn version`): Keptn CLI version: 0.7.1
* Kubernetes Cloud Provider (e.g., GKE, AKS):GKE, EKS, minikube
* Kubernetes version (`kubectl version`):Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T19:10:59Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"darwin/amd64"}

**Affected Component**
start evaluation

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
I have been testing version 7 for a quality gates only scenario where the services are deployed using our own deployment processes.  The deployment YAML contains the following as per the instructions for using keptn for external deployments:

        env:
        - name: DT_CUSTOM_PROP
          value: "keptn_project=test-project keptn_service=test-service keptn_stage=pvs"

Those three tags are created properly and show in dynatrace as they should.

When we try to execute the keptn send event start-evaluation --project=test-project --stage=pvs --service=test-service --timeframe=5m --suppress-websocket the evaluation fails with this message:

"Dynatrace Metrics API returned 0 result values, expected 1. Please ensure the response contains exactly one value (e.g., by using :merge(0):avg for the metric)

I looking in to this, we found that the request you are sending to the API has an additional tag referenced called keptn_deployment and is being sent to the API as blank.  Since there is no keptn_deployment tag in Dynatrace, the API returns the zero result.

https://{redacted}.live.dynatrace.com/api/v2/metrics/query/?entitySelector=tag(keptn_project:test-project),tag(keptn_stage:pvs),tag(keptn_service:test-service),tag(keptn_deployment:),type(SERVICE)&from=1601306835000&metricSelector=builtin:service.response.time:merge(0):percentile(95)&resolution=Inf&scope=tag(keptn_project:test-project),tag(keptn_stage:pvs),tag(keptn_service:test-service),tag(keptn_deployment:)&to=1601307135000
 
If we remove the keptn_deployment tag from the query and run it through postman, results are returned as expected.

The shipyard.yaml for a externally deployed service only contains the stage and not a deployment strategy so that is helping to lead to this error in my opinion.

**To Reproduce**
externally deploy a service using only the three DT tags mentioned and then create the quality gates only setup in keptn.  Issue a start evaluation for that project.

**Expected behavior**
Metrics would be successfully returned for the three DT custom tags used

**Current behavior**
zero reults returned

**Screenshots**
see bug description

**Comment by cjmckenna** [comment] 2020-09-28 18:47
UPDATE:  We added a deployment strategy of direct to the shipyard file and then updated our deployment.yaml file to add the keptn_deployment=direct.

This allowed the evaluation to work properly.  Either the documentation needs to be updated to state this tag is necessary for an external deployment, or the evaluation needs to exclude that tag when doing an SLI evaluation on an external deployment.

**Comment by agrimmer** [comment] 2020-10-01 06:48
Thank you for this issue and especially debugging the root cause!

You are right, that the default SLI metrics also contain a `keptn_deployment`, which is required if Keptn is used as  deployment tool.
In your case, please use a custom set of SLIs, which does not contain `keptn_deployment`. Please checkout out https://keptn.sh/docs/0.7.x/monitoring/dynatrace/sli_provider/#configure-custom-dynatrace-slis

Furthermore, we are currently improving the docs for Quality Gates, which will hopefully make this more clear.
I am closing this issue but please feel free to re-open/ask further questions.

**Closed by agrimmer** 2020-10-01 06:48 UTC
