### ISSUE TITLE
For user_managed charts the Helm-Service should not handle rollbacks or releases

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#3610] opened 2021-03-25 09:57 UTC
When using the option "user_managed" the helm-service should simply apply the helm chart during the deployment task.
in case of rollback or release my opinion is that it doesnt make sense for the helm-service to do anything because the rollback and release tasks are really for use cases where we do blue/greens or where we use other tools such as argo-rollouts for promotion or abortion of rollouts. These are then however handled specially by these services, e.g: argo-service

The impact of this current behavior is that rollbacks always fail when using the helm-service for user_managed deploymentstrategy. See this output here
![image](https://user-images.githubusercontent.com/675886/112454138-ad5b1c80-8d58-11eb-8351-8e351de639c5.png)

I therefore suggest that the Helm Service ONLY becomes active for "release" and "rollback" in case we have a "blue_green_service" deploymentstrategy

**Comment by warber** [comment] 2021-04-20 12:26
Duplicate of #3655

**Closed by warber** 2021-04-20 12:26 UTC
Labels: area:helm-service
