### ISSUE TITLE
Keptn on minikube on gcp unable to authenticate

### ISSUE THREAD

**Issue by kristofre** [keptn/keptn#1389] opened 2020-02-19 09:20 UTC
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, OSX, Windows): Ubuntu 18.04
* Keptn Version (`keptn version`): 0.6.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): Minikube 1.2.0 running k8s 1.15

Running keptn on Minikube 1.2.0 which is installed on a n1-standard-16 GCE instance. Keptn CLI and kubectl are also installed on the GCE instance.

**Affected Component**

* [ ] Docs
* [X] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

After installation the CLI is unable to authenticate:
```
keptn@kqg-minikube-c19b5c95618e38c0:~$ keptn auth --endpoint=http://api.keptn.$(kubectl get cm -n keptn keptn-domain -ojsonpath={.data.app_domain}) --api-token=$(kubectl get secret keptn-api-token -n keptn -ojsonpath={.data.keptn-api-token} | base64 --decode)
Starting to authenticate
Authentication was unsuccessful. Post https://api.keptn.10.0.2.15.xip.io:31630/v1/auth: dial tcp 10.0.2.15:31630: i/o timeout
Error: Authentication was unsuccessful. Post https://api.keptn.10.0.2.15.xip.io:31630/v1/auth: dial tcp 10.0.2.15:31630: i/o timeout
```

**To Reproduce**

Create VM on GCE using nested virtualization. Terraform scripts on https://github.com/dynatrace-ace/keptnqualitygates-minkube can be used as a base

Create Minikube cluster on GCE instance:
minikube start --cpus 12 --memory 48000

Install keptn quality gates
`keptn install --platform=kubernetes --use-case=quality-gates --gateway=NodePort`

**Expected behavior**

Authentication successful 

**Current behavior**

Authentication Fails

**Comment by christian-kreuzberger-dtx** [comment] 2020-02-20 14:10
Thanks for the report. Just to rule out a network problem and to further dig into the problem, can you please show the output of the following command:

```console
kubectl get services -n ingress-nginx
```

and
```console
kubectl get ingresses --all-namespaces
```

and
```console
 kubectl get pods --all-namespaces | grep nginx
```

**Comment by kristofre** [comment] 2020-02-21 08:26
`keptn@kqg-minikube-f2842c400633b3b7:~$ kubectl get services -n ingress-nginx
NAME            TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
ingress-nginx   NodePort   10.105.69.96   <none>        80:30087/TCP,443:32233/TCP   19h`

`keptn@kqg-minikube-f2842c400633b3b7:~$ kubectl get ingresses --all-namespaces
NAMESPACE   NAME          HOSTS                                  ADDRESS        PORTS     AGE
keptn       api-ingress   api.keptn.10.0.2.15.xip.io,api.keptn   10.105.69.96   80, 443   19h`

`keptn@kqg-minikube-f2842c400633b3b7:~$ kubectl get pods --all-namespaces | grep nginx
ingress-nginx     nginx-ingress-controller-69969b98db-qk5pq                         1/1     Running   0          19h`

**Comment by christian-kreuzberger-dtx** [comment] 2020-02-21 13:46
I was able to reproduce this issue with Keptn 0.6.0 on my local Ubuntu 18.04 with Minikube 1.2 and Virtualbox 5.2.

```
Authentication was unsuccessful. Post https://api.keptn.10.0.2.15.xip.io:32674/v1/auth: dial tcp 10.0.2.15:32674: i/o timeout
```

However, the error at hand is that 10.0.2.15 is the internal IP of Minikube, which is correct, as you are using `--gateway=NodePort`.

Exposing a service via NodePort will expose it with the IP address of the node (in this case: a nested VM that runs minikube). It doesn't matter if you do that on GCE or locally, the result will be the same: you will not be able to access it unless you configure some network forwarding rules by yourself (or using [`minikube service` (see official tutorial)](https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-service)).

If you just install Keptn normally (which uses a loadbalancer as a gateway) and run `minikube tunnel` (as we have it [documented for Minikube 1.2](https://keptn.sh/docs/0.6.0/installation/setup-keptn/#setup-kubernetes-cluster)) then you should not run into problems.

Alternatively, if you really need to use NodePort, you can always just use minikube with `minikube start --vm-driver=none` like we do in our [integration tests](https://github.com/keptn/keptn/blob/master/test/utils/minikube_create_cluster.sh) - on GCE you might not even need nested virtualization for this.

Last but not least, since Keptn 0.6.0 we also have [experimental support for Microk8s](https://keptn.sh/docs/0.6.0/reference/microk8s/), which should also work with the use-case you are describing.

**Comment by christian-kreuzberger-dtx** [comment] 2020-02-26 14:19
Closing this as the issue seems to be fixed.

**Closed by christian-kreuzberger-dtx** 2020-02-26 14:19 UTC
