### ISSUE TITLE
evaluation fails with "75 < 75" because of key-sli

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#5900] opened 2021-11-03 12:07 UTC
Using Keptn 0.10.0-next.2, I managed to create an interesting evaluation result:

![image](https://user-images.githubusercontent.com/56065213/140056712-cb33e80a-bf57-4385-9589-ae45cc328e43.png)

The evaluation is failing correctly, because one of my Key-SLIs is failing (more details on that below), but the display "**75** < 75" seems to be wrong (the number in bold is the achieved score).

# Expected behaviour

I would expect the evaluation to display as "fail" because a Key SLI has failed, without comparing it to anything else. We do something similar (but in the positive direction with a "success") when no SLO file is present, e.g.:

![image](https://user-images.githubusercontent.com/56065213/140061837-5fc95890-c69a-459f-b548-83c63c2d8405.png)

# Reproducability / More details

## Step 1: Run Quickstart Step 5

I've run into this issue by following [Quickstart Step 5](https://keptn.sh/docs/quickstart/) (Perform a multi-stage delivery) on my Keptn 0.10.0-next.2:

This is the SLO file used:
```
---
spec_version: '0.1.0'
comparison:
  compare_with: "single_result"
  include_result_with_score: "pass"
  aggregate_function: avg
objectives:
  - sli: http_response_time_seconds_main_page_sum
    displayName: "HTTP Respone Time"
    pass:
      - criteria:
          - "<=0.4"
    warning:
      - criteria:
          - "<=0.1"
  - sli: request_throughput
    displayName: "Request Throughput"
    pass:
      - criteria:
          #- "<=+100%"
          - ">=-80%"
  - sli: go_routines
    displayName: "Go Routines"
    key_sli: true
    pass:
      - criteria:
          - "<=90"
  - sli: failing_request
    displayName: "Failing Requests"
    pass:
      - criteria:
          - "< 10"
total_score:
  pass: "90%"
  warning: "75%"
```

This is the CloudEvent generated (I've slimmed it down a bit for readability):
```
{
  "data": {
    "evaluation": {"comparedEvents": ["f0b7eeb0-0afe-4f0a-aa51-362eaef2ff7e"],
      "indicatorResults": [
        {
          "displayName": "HTTP Respone Time",
          "keySli": false,
          "passTargets": [
            {
              "criteria": "<=0.4",
              "targetValue": 0.4,
              "violated": false
            }
          ],
          "score": 1,
          "status": "pass",
          "value": {
            "metric": "http_response_time_seconds_main_page_sum",
            "success": true,
            "value": 0.20115315268094103
          },
          "warningTargets": [
            {
              "criteria": "<=0.1",
              "targetValue": 0.1,
              "violated": true
            }
          ]
        },
        {
          "displayName": "Request Throughput",
          "keySli": false,
          "passTargets": [
            {
              "criteria": ">=-80%",
              "targetValue": 0,
              "violated": false
            }
          ],
          "score": 1,
          "status": "pass",
          "value": {
            "metric": "request_throughput",
            "success": true,
            "value": 169.23333333333332
          },
          "warningTargets": null
        },
        {
          "displayName": "Go Routines",
          "keySli": true,
          "passTargets": [
            {
              "criteria": "<=90",
              "targetValue": 90,
              "violated": true
            }
          ],
          "score": 0,
          "status": "fail",
          "value": {
            "metric": "go_routines",
            "success": true,
            "value": 253
          },
          "warningTargets": null
        },
        {
          "displayName": "Failing Requests",
          "keySli": false,
          "passTargets": [
            {
              "criteria": "< 10",
              "targetValue": 10,
              "violated": false
            }
          ],
          "score": 1,
          "status": "pass",
          "value": {
            "metric": "failing_request",
            "success": true,
            "value": 0
          },
          "warningTargets": null
        }
      ],
      "result": "fail",
      "score": 75,
    },
    "message": "Evaluation failed since the calculated score of 75 is below the target value of 90",
    "project": "podtatohead",
    "result": "fail",
    "service": "helloservice",
    "stage": "hardening",
    "status": "succeeded"
  },
  "source": "lighthouse-service",
  "type": "sh.keptn.event.evaluation.finished",
}
```

## Step 2: Change SLO file

Furthermore, I've changed the SLO file to have

```
total_score:
  pass: "10%"
  warning: "5%"
```

which will make it even more obvious:
![image](https://user-images.githubusercontent.com/56065213/140061635-a816cb40-1fdb-4d18-9d69-f78e01d44436.png)

In addition, I've checked the message provided by lighthouse-service, which also seems to be wrong/misleading:

```
    "message": "Evaluation failed since the calculated score of 75 is below the target value of 10",
    "result": "fail",
```

**Comment by thisthat** [comment] 2022-01-05 15:47
I tried to quickly reproduce this in Keptn 0.11.4 and it looks like it doesn't occur anymore
![image](https://user-images.githubusercontent.com/992621/148246595-79103a69-fbda-49bf-a630-ceb9020b41d1.png)

Could you please have another look @christian-kreuzberger-dtx if this is fixed?

**Comment by thisthat** [comment] 2022-01-19 15:25
I am closing this. If you encounter it again, please reopen the issue.

**Comment by christian-kreuzberger-dtx** [comment] 2022-04-11 09:38
Re-opening this, as @kristofre has reproduced this:
![image](https://user-images.githubusercontent.com/56065213/162711293-247cf841-b1ef-45d5-a226-04c65d544549.png)

**Closed** 2022-07-07 12:01 UTC
Labels: type:bug, bridge.2.0
