### ISSUE TITLE
Keptn on OpenShift 4.4

### ISSUE THREAD

**Issue by marcredhat** [keptn/keptn#2157] opened 2020-08-01 05:28 UTC
I have Keptn running on OpenShift 4.4, rough notes at https://github.com/marcredhat/dynatrace/blob/master/keptn.adoc. 

Keptn dashboards get created in Dynatrace but seem empty, please see https://github.com/marcredhat/dynatrace/blob/master/images/keptn_dashboard.png

**Comment by johannes-b** [comment] 2020-08-05 05:39
Hi @marcredhat, 

great that you have Keptn running on OpenShift 4.4. The notes you posted look very good and there is no step missing as far I can estimate it. 

The issue you are mentioning is more related to the Dynatrace integration rather Keptn itself. But let's dig into it.
1. Have the services been successfully deployed by Keptn? A screenshot of the Keptn Bridge, or a glimpse into the namespace of the project can help to figure that out (according to your notes you created the projects: `marc2`, `sockshop111`, and `sockshopgate` --> then there should be namespaces with these names)  
1. Are you services monitored? Go to Dynatrace and see: *Transaction and service*
    - If not, please double-check the PAAS token. (The API token is valid and works otherwise the tagging rules and dashboards would not have been created.)

**Comment by marcredhat** [comment] 2020-08-05 22:46
Thanks @johannes-b ! 
The namespaces exist but I cannot onboard services / add resources. Please see the errors below:

1) 
keptn onboard service carts --project=sockshopgate --chart=./carts
Starting to onboard service
Handling connection for 8080
ID of Keptn context: 6d765ffa-2bb5-44e1-9901-886fc39d1f79
Handling connection for 8080
Error when getting deployment strategies: Get http://configuration-service:8080/v1/project/sockshopgate/resource/shipyard.yaml: dial tcp 172.30.241.251:8080: connect: connection refused

keptn add-resource --project=sockshopgate --service=carts --stage=test --resource=jmeter/load.jmx --resourceUri=jmeter/basiccheck.jmx
Adding resource jmeter/load.jmx to service carts in stage test in project sockshopgate
Handling connection for 8080
....
E0805 18:41:09.033774 2464489 portforward.go:233] lost connection to pod
Error: Resource jmeter/load.jmx could not be uploaded: Post http://localhost:8080/api/configuration-service/v1/project/sockshopgate/stage/test/service/carts/resource: EOF

**Comment by johannes-b** [comment] 2020-08-07 12:15
For getting a closer look into Keptn and what is going on, can you please run the command: `keptn generate support-archive --dir=` (please see here: https://keptn.sh/docs/0.7.x/reference/cli/commands/keptn_generate_support-archive/) 
This command collects the logs of all Keptn services. 

Can you then send me the logs via Slack for example? (slack.keptn.sh)

**Comment by marcredhat** [comment] 2020-08-07 19:38
Thanks Johannes, I sent you the support archive via direct message on Slack.
The project gets created  etc (please see full details below).
However, I still get "websocket connection timed out" when I do a "keptn send event new-artifact" 


oc get pods
NAME                                    READY   STATUS    RESTARTS   AGE
api-gateway-nginx-5b865b66b8-j28v9      1/1     Running   0          89m
api-service-6d86cb4f88-vqkk4            1/1     Running   0          89m
bridge-6594f6b8c-dcg9c                  1/1     Running   0          89m
configuration-service-f6856c58f-sgr5w   2/2     Running   0          38m
eventbroker-go-5674d9646d-nhw5m         1/1     Running   0          89m
helm-service-85f8bf5fd6-jt4hw           2/2     Running   4          89m
keptn-nats-cluster-0                    3/3     Running   0          88m
lighthouse-service-6d4b5dcd9-kvfbx      2/2     Running   5          89m
mongodb-7dcd49b688-pr5zd                1/1     Running   0          38m
mongodb-datastore-647b5bc584-wrjq2      2/2     Running   4          89m
remediation-service-cf4b7b97f-jdntb     2/2     Running   4          89m
shipyard-service-5c98f89f4c-tds85       2/2     Running   5          89m


keptn create project sockshopgate --shipyard=./shipyard.yaml
WARNING: Creating a project without Git upstream repository is not recommended.
You can configure a Git upstream repository using:

keptn update project PROJECTNAME --git-user=GIT_USER --git-token=GIT_TOKEN --git-remote-url=GIT_REMOTE_URL

Starting to create project
Handling connection for 8080
ID of Keptn context: 478eb5b8-ee57-4062-bcec-09eeb672a28c
Handling connection for 8080
Project sockshopgate created
Stage dev created
Stage staging created
Stage production created
Shipyard successfully processed


oc project sockshopgate
Now using project "sockshopgate" on server "https://api.apps.ocp4.local:6443".


keptn onboard service carts --project=sockshopgate --chart=./carts
Starting to onboard service
Handling connection for 8080
ID of Keptn context: e94ae8ef-876c-453b-a83c-ece0dbe51575
Handling connection for 8080
Create umbrella Helm Chart for project sockshopgate
Creating new Keptn service carts in stage dev
Creating new Keptn service carts in stage staging
Inject Istio to the sockshopgate-staging namespace for blue-green deployments
Creating new Keptn service carts in stage production
Inject Istio to the sockshopgate-production namespace for blue-green deployments
Finished creating service carts in project sockshopgate

keptn add-resource --project=sockshopgate --service=carts --stage=dev --resource=jmeter/load.jmx --resourceUri=jmeter/basiccheck.jmx
Adding resource jmeter/load.jmx to service carts in stage dev in project sockshopgate
Handling connection for 8080
Resource has been uploaded.


keptn add-resource --project=sockshopgate --stage=dev --service=carts --resource=jmeter/basiccheck.jmx --resourceUri=jmeter/basiccheck.jmx
Adding resource jmeter/basiccheck.jmx to service carts in stage dev in project sockshopgate
Handling connection for 8080
Resource has been uploaded.

oc projects | grep socks
  * sockshopgate
    sockshopgate-dev
    sockshopgate-production
    sockshopgate-staging


  keptn send event new-artifact --project=sockshopgate --service=carts --image=docker.io/keptnexamples/carts --tag=0.11.1
  Availability of provided image cannot be checked.
  Starting to send a new-artifact-event to deploy the service carts in project sockshopgate in version keptnexamples/carts:0.11.1
  Handling connection for 8080
  ID of Keptn context: 1e4012e2-b82a-4c1b-acd8-82c261071014
  Handling connection for 8080Warning: Websocket connection timed out

Same with a local image:
keptn send event new-artifact --project=sockshopgate --service=carts --image=localhost/hercules 
Handling connection for 8080Warning: Websocket connection timed out

**Comment by johannes-b** [comment] 2020-08-10 06:51
Hi @marcredhat 

according to your current comment, you are not facing the next problems anymore:  
* `keptn onboard service carts --project=sockshopgate --chart=./carts` --> **Error when getting deployment strategies: Get http://configuration-service:8080/v1/project/sockshopgate/resource/shipyard.yaml: dial tcp 172.30.241.251:8080: connect: connection refused**
* `keptn add-resource --project=sockshopgate --service=carts --stage=test --resource=jmeter/load.jmx --resourceUri=jmeter/basiccheck.jmx` --> **Error: Resource jmeter/load.jmx could not be uploaded: Post http://localhost:8080/api/configuration-service/v1/project/sockshopgate/stage/test/service/carts/resource: EOF**

What did you change to make them work? 

--- 

What I can see now is, that you could successfully: 
- create a project: `keptn create project sockshopgate --shipyard=./shipyard.yaml` :heavy_check_mark:
- onboard a service: `keptn onboard service carts --project=sockshopgate --chart=./carts` :heavy_check_mark:
- add a resource: `keptn add-resource --project=sockshopgate --service=carts --stage=dev --resource=jmeter/load.jmx --resourceUri=jmeter/basiccheck.jmx` :heavy_check_mark:

Then you triggered a deployment with: 
- keptn send event new-artifact --project=sockshopgate --service=carts --image=docker.io/keptnexamples/carts --tag=0.11.1

I'm now super curious whether there are pods running in your namespace (project) `sockshopgate-dev`, `sockshopgate-staging`, and `sockshopgate-production`. Can you let me know?

**Comment by johannes-b** [comment] 2020-08-10 06:58
Thanks for the logs you sent to me. I investigated them and think that I found the current blocker. 

I'm I right that you installed Keptn via: `keptn install --platform=openshift` (as stated here: https://github.com/marcredhat/dynatrace/blob/master/keptn.adoc)?
(--> This installs the control-plane of Keptn, but not the components for Continous Delivery.)

Please execute the command: `keptn install --use-case=continuous-delivery --platform=openshift`
(--> This installs the services required for a `keptn send event new-artifact`.)

**Comment by marcredhat** [comment] 2020-08-10 07:12
Thanks @johannes-b ! 
keptn install --use-case=continuous-delivery --platform=openshift results in 2 errors (please also see my comments at the end)
Helm Chart used for Keptn installation: https://storage.googleapis.com/keptn-installer/keptn-0.7.0.tgz
.....
Istio is required for the continuous-delivery use case, but could not be found in your cluster in namespace istio-system.
Please install Istio as described in the Istio docs: https://istio.io/latest/docs/setup/getting-started/
Existing Keptn installation found in namespace keptn

Do you want to overwrite this installation? (y/n)
y
Start upgrading Helm Chart keptn in namespace: keptn
Could not complete Keptn installation: Error when installing/upgrading Helm Chart keptn in namespace keptn: "keptn" has no deployed releases
Error: Error when installing/upgrading Helm Chart keptn in namespace keptn: "keptn" has no deployed releases

My comments:
1) Re Istio, I have OpenShift Mesh up and running as shown at https://github.com/marcredhat/dynatrace/blob/master/servicemesh.adoc
The differences between OpenShift 4.4 Service Mesh and upstream Istio are explained at https://access.redhat.com/documentation/en-us/openshift_container_platform/4.4/html/service_mesh/service-mesh-architecture#ossm-vs-community
2) "keptn" has no deployed releases. Not quite sure what this means and how to fix...

Thanks,
Marc

**Comment by johannes-b** [comment] 2020-08-10 17:35
Comment 1.) Keptn requires Istio for doing a blue/green deployment of your service. In more details, the two CRDs are required:
   - [DestinationRule](https://istio.io/latest/docs/reference/config/networking/destination-rule/)
   - [VirtualService](https://istio.io/latest/docs/reference/config/networking/virtual-service/)

But let`s get to the point, where blue/green deployments come into play. 

Comment 2.) The error **"keptn" has no deployed releases.** is returned by Helm, which is used for the upgrade. Would it be possible to execute a `keptn uninstall` and then a `keptn install --use-case=continuous-delivery --platform=openshift`? This deletes Keptn from your cluster and re-installs it. 
(The documentation of these two commands is provided here: https://keptn.sh/docs/0.7.x/reference/cli/commands/)

**Comment by marcredhat** [comment] 2020-08-11 07:07
I created a fresh cluster and deployed OpenShift Service Mesh in istio-system. All good there.
Keptn seems happy too:
oc get pods
NAME                                                              READY   STATUS    RESTARTS   AGE
api-gateway-nginx-5bc6f54d4b-dr24g                                1/1     Running   0          101m
api-service-55d4c499fd-7j627                                      1/1     Running   0          101m
bridge-559f9988c7-wnttg                                           1/1     Running   0          101m
configuration-service-865d89f78f-zgshf                            2/2     Running   0          101m
eventbroker-go-dcf997974-zlftw                                    1/1     Running   0          101m
gatekeeper-service-678f556955-l6nwc                               2/2     Running   2          101m
helm-service-6946fb9b8d-vtgn9                                     2/2     Running   2          101m
helm-service-continuous-deployment-distributor-567cc995bd-8xflq   1/1     Running   2          101m
jmeter-service-669848d4f8-kbg9s                                   2/2     Running   1          101m
keptn-nats-cluster-0                                              3/3     Running   0          101m
lighthouse-service-5bb8698f9-wc8df                                2/2     Running   2          101m
mongodb-datastore-cd457f886-nv5bj                                 2/2     Running   2          101m
mongodb-dbff8b66c-pnhzm                                           1/1     Running   0          101m
openshift-route-service-7f57d79955-rpzkh                          2/2     Running   2          101m
remediation-service-5f44c6779c-4tpqh                              2/2     Running   2          101m
shipyard-service-6c989977d5-q9xgk                                 2/2     Running   2          101m

But now "keptn create project" commands result in:
Starting to create project
Handling connection for 8080
ID of Keptn context: 17d68505-05f9-4a23-abc6-b53946bb7425
Handling connection for 8080
Project marctest created
Creating stage staging failed. Could not create stage..

**Comment by marcredhat** [comment] 2020-08-11 17:49
UPDATE: Worked fine after I did a first commit to the project's github repo
keptn create project marc1111 --shipyard ./shipyard.yaml --git-user=<git user> --git-token=<git token>  --git-remote-url=https://github.com/marcredhat/marc1111.git
Starting to create project
Handling connection for 8080
ID of Keptn context: <xxx>
Handling connection for 8080
Project marc1111 created
Stage dev created
Stage staging created
Stage production created
Shipyard successfully processed

**Comment by marcredhat** [comment] 2020-08-11 18:14
So Keptn works fine on OpenShift 4.4 and 4.5, we can use the above to create an OpenShift 4.4+ / Keptn tutorial.
The only remaining problem is with the Keptn/Dynatrace integration:
oc logs dynatrace-service-775c6b876c-j42rx
##########
branch: 0.7.0
repository: https://github.com/keptn-contrib/dynatrace-service
commitlink: https://github.com/keptn-contrib/dynatrace-service/commit/2a7b0e6f4cf462b375b06cdec5aa6fd14b3159f4
repolink: https://github.com/keptn-contrib/dynatrace-service/tree/2a7b0e6f4cf462b375b06cdec5aa6fd14b3159f4
timestamp: 20200507.0740
version: 0.7.0
##########
2020/08/11 18:04:11 Port = 8080; Path=/
{"timestamp":"2020-08-11T18:05:44.287445048Z","logLevel":"DEBUG","message":"Received event: sh.keptn.event.monitoring.configure"}
{"timestamp":"2020-08-11T18:05:44.298770382Z","logLevel":"ERROR","message":"Opening WebSocket connection failed:websocket: bad handshake"}
{"timestamp":"2020-08-11T18:07:27.669959071Z","logLevel":"DEBUG","message":"Received event: sh.keptn.event.monitoring.configure"}
{"timestamp":"2020-08-11T18:07:27.680820317Z","logLevel":"ERROR","message":"Opening WebSocket connection failed:websocket: bad handshake"}
{"timestamp":"2020-08-11T18:10:24.316111157Z","logLevel":"DEBUG","message":"Received event: sh.keptn.event.monitoring.configure"}
{"timestamp":"2020-08-11T18:10:24.324921055Z","logLevel":"ERROR","message":"Opening WebSocket connection failed:websocket: bad handshake"}

**Comment by marcredhat** [comment] 2020-08-12 05:54
Updated the instructions at https://github.com/marcredhat/dynatrace/blob/master/keptn.adoc
The carts app and database get deployed in the -dev namespace. All good there.
The -staging and -production namespaces get created but remain empty.  
I'd love to test the quality gates but not sure how to proceed given the above.

**Comment by johannes-b** [comment] 2020-08-12 06:17
Hi @marcredhat, 
that are really great news! 

The problem you are facing with the Keptn/Dynatrace integration (aka. the `dynatrace-service`) is something we can address independently from the Keptn releasing cycle and fix with a patch that makes the WebSocket communication from the dynatrace-service to the api-service more robust. I will reach out to the team. 

* **The -staging and -production namespaces get created but remain empty.**: Can you take a look at the 'staging' or 'production' branch in your Git repository and check out whether there are two folders (carts and carts-generated) in: carts/helm/. Can you find the folders? 

* **I'd love to test the quality gates but not sure how to proceed given the above.**: I would recommend setting this up for the `dev` stage as you have a deployed service there.
   1. You need to deploy the `dynatrace-sli-service`:  https://raw.githubusercontent.com/keptn-contrib/dynatrace-sli-service/0.4.1/deploy/service.yaml (this service is responsible for fetching the data from Dynatrace)
   1. Add the SLO file for the carts service to the `dev` stage: `keptn add-resource --project=sockshop --stage=dev --service=carts --resource=slo-quality-gates.yaml --resourceUri=slo.yaml`
   1. Add the SLI file: `keptn add-resource --project=sockshop --stage=dev --service=carts --resource=sli-config-dynatrace.yaml  --resourceUri=dynatrace/sli.yaml`

Did you deploy Dynatrace OneAgent operator on your cluster and is your carts service monitored? 
- Please follow the instructions from: https://www.dynatrace.com/support/help/technology-support/cloud-platforms/kubernetes/deploy-oneagent-k8/

**Comment by marcredhat** [comment] 2020-08-12 07:08
1) I only have the 2 folders (carts and carts-generated) in the -dev branch.
2) The quality gates install using your 3 commands above seems to have worked. I added the results to the "Quality gates" paragraph at https://github.com/marcredhat/dynatrace/blob/master/keptn.adoc
In the -dev branch, keptn added:
---
spec_version: '1.0'
indicators:
  throughput: "builtin:service.requestCount.total:merge(0):sum?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE),tag(keptn_deployment:$DEPLOYMENT)"
  error_rate: "builtin:service.errors.total.count:merge(0):avg?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE),tag(keptn_deployment:$DEPLOYMENT)"
  response_time_p50: "builtin:service.response.time:merge(0):percentile(50)?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE),tag(keptn_deployment:$DEPLOYMENT)"
  response_time_p90: "builtin:service.response.time:merge(0):percentile(90)?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE),tag(keptn_deployment:$DEPLOYMENT)"
  response_time_p95: "builtin:service.response.time:merge(0):percentile(95)?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE),tag(keptn_deployment:$DEPLOYMENT)"

3) Yes. OneAgent pods are running on all nodes.

**Comment by johannes-b** [comment] 2020-08-12 08:29
I assume that OpenShift Service Mesh might be the reason why Keptn cannot create the Helm charts for `staging` and `production`. But let's dig into that problem when the quality gate in `dev` works. 

--- 

In the meanwhile, I figured out that you deployed an old version of the dynatrace-service. According to your logs, you deployed `dynatrace-service:0.7.0`, but the new version is `dynatrace-service:0.8.0` (I'm sorry, if there is still a link to dynatrace-service:0.7.0 combined with Keptn 0.7.0)

* Can you please delete the dynatrace-service.
* And install it, as explained here: https://keptn.sh/docs/0.7.x/monitoring/dynatrace/install/#install-dynatrace-keptn-integration
   * Important, please use: `https://raw.githubusercontent.com/keptn-contrib/dynatrace-service/0.8.0/deploy/service.yaml`
* Then execute: `keptn configure monitoring dynatrace --project=sockshop` again.

**Comment by marcredhat** [comment] 2020-08-12 15:16
keptn configure monitoring dynatrace --project=marc1111
Handling connection for 8080
ID of Keptn context: 7e62a412-c5b8-4958-871f-6683b576abe6
Handling connection for 8080
Configuring Dynatrace monitoring
Dynatrace OneAgent Operator is installed on cluster
Setting up auto-tagging rules in Dynatrace Tenant
Tagging rule keptn_service already exists
Tagging rule keptn_stage already exists
Tagging rule keptn_project already exists
Tagging rule keptn_deployment already exists
Setting up problem notifications in Dynatrace Tenant
Checking Keptn alerting profile availability
Keptn alerting profile available
Could not retrieve shipyard for project marc1111: Resource not found

**Comment by marcredhat** [comment] 2020-08-12 15:37
With a new project, I get:
keptn create project marc2222 --shipyard ./shipyard.yaml --git-user=xxxx --git-token=xxx --git-remote-url=https://github.com/xxxx/marc2222
Starting to create project
Handling connection for 8080
ID of Keptn context: c5f578bb-7da0-4a60-b3fc-6cb9babbdc74
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Creating project marc2222 failed. Post http://configuration-service:8080/v1/project: EOF

**Comment by marcredhat** [comment] 2020-08-12 16:36
oc logs configuration-service-865d89f78f-qzcg7 -c configuration-service
MongoDB client lost connection. Attempt reconnect.
Could not cast &{{} <nil> [] 0xc00010cf50} to *models.Project

**Comment by johannes-b** [comment] 2020-08-14 06:52
(For someone who is following this thread, please also consider this comment: https://github.com/keptn/keptn/issues/1969#issuecomment-673915162)

**Comment by johannes-b** [comment] 2020-08-14 07:04
Comment from @marcredhat in https://github.com/keptn/keptn/issues/1969#issuecomment-673915162: "I see my quality gate results in Dynatrace." 

That's great! Because then we know that Keptn is working fine and the Keptn/Dynatrace integration (with the dynatrace-service and dynatrace-sli-serivce) works too. 

Please don't get confused about the log messages from the dynatrace-service:
```
...
{"timestamp":"2020-08-14T06:39:10.29066251Z","logLevel":"INFO","message":"Loaded Config from dynatrace.conf.yaml: \u0026{0.1.0 }"}
{"timestamp":"2020-08-14T06:39:10.290684499Z","logLevel":"DEBUG","message":"Found dynatrace.conf.yaml with DTCreds: "}
{"timestamp":"2020-08-14T06:39:10.313321833Z","logLevel":"DEBUG","message":"Couldn't find any dynatrace specific secrets in namespace keptn"}
...
```
This is a feature of the dynatrace-service that would allow fetching data from a Dynatrace tenant other than the one you use for monitoring your sample app. As long as you see the events in Dynatrace, we know that the Keptn/Dynatrace integration works as expected. 

Can you also take a look into the Keptn Bridge (available at: `http://your-keptn-endpoint/bridge`) to see the result of the quality gate evaluation there?

**Comment by marcredhat** [comment] 2020-08-14 07:13
Thanks @johannes-b I can now consistently deploy on OpenShift 4.5  and 
I see my quality gate results in Dynatrace.
Please see
https://raw.githubusercontent.com/marcredhat/dynatrace/master/images/dev3.png
https://raw.githubusercontent.com/marcredhat/dynatrace/master/images/dev4.png
https://raw.githubusercontent.com/marcredhat/dynatrace/master/images/qualitygateresults.png
https://raw.githubusercontent.com/marcredhat/dynatrace/master/images/dev2.png
https://raw.githubusercontent.com/marcredhat/dynatrace/master/images/dev1.png

The bridge says I have no projects:
https://raw.githubusercontent.com/marcredhat/dynatrace/master/images/bridge.png


keptn configure monitoring dynatrace --project=keptnopenshift45 --service=carts
ID of Keptn context: b57812be-9120-4b7a-8aa0-c76442770cd2
Configuring Dynatrace monitoring
Dynatrace OneAgent Operator is installed on cluster
Setting up auto-tagging rules in Dynatrace Tenant
Tagging rule keptn_service already exists
Tagging rule keptn_stage already exists
Tagging rule keptn_project already exists
Tagging rule keptn_deployment already exists
Setting up problem notifications in Dynatrace Tenant
Checking Keptn alerting profile availability
Keptn alerting profile available
Creating Dashboard for project keptnopenshift45
Dynatrace dashboard created successfully. You can view it here: https://eye15053.live.dynatrace.com/#dashboards
Creating custom metric events for project SLIs
Failed to get custom queries for project keptnopenshift45
Resource not found
Creating custom metric events for project SLIs
No SLOs defined for service carts-db in stage production. Skipping creation of custom metric events.
Dynatrace Monitoring setup done

**Comment by marcredhat** [comment] 2020-08-14 16:47
In the dynatrace-service logs (please see below), it seems that get-sli events are not sent to Dynatrace. 
Also, nothing gets deployed in -staging and -production.

{"timestamp":"2020-08-14T06:56:14.669579752Z","logLevel":"INFO","message":"Sending event to Dynatrace API using dtCreds: dynatrace-credentials-keptnopenshift45"}
{"timestamp":"2020-08-14T06:56:14.948061044Z","logLevel":"DEBUG","message":"Dynatrace service returned status 200 OK"}
{"timestamp":"2020-08-14T06:56:14.948168402Z","logLevel":"DEBUG","message":"Dynatrace API has accepted the event"}
{"timestamp":"2020-08-14T06:56:14.948201889Z","logLevel":"DEBUG","message":"Response Body:{\"storedEventIds\":[4708073990361083874,-2303865422081304986,415550376662715760,6209218478970187478],\"storedIds\":[\"4708073990361083874_1597388175106\",\"-2303865422081304986_1597388175106\",\"415550376662715760_1597388175106\",\"6209218478970187478_1597388175106\"],\"storedCorrelationIds\":[]}"}
{"timestamp":"2020-08-14T06:56:14.948271454Z","logLevel":"INFO","message":"Sending event to Dynatrace API using dtCreds: dynatrace-credentials-keptnopenshift45"}
{"timestamp":"2020-08-14T06:56:15.047088808Z","logLevel":"DEBUG","message":"Dynatrace service returned status 200 OK"}
{"timestamp":"2020-08-14T06:56:15.047225846Z","logLevel":"DEBUG","message":"Dynatrace API has accepted the event"}
{"timestamp":"2020-08-14T06:56:15.047285683Z","logLevel":"DEBUG","message":"Response Body:{\"storedEventIds\":[5101987050463611697,-4261340289338490617,2538393843259250260,-4132496686703652614],\"storedIds\":[\"5101987050463611697_1597388175210\",\"-4261340289338490617_1597388175210\",\"2538393843259250260_1597388175210\",\"-4132496686703652614_1597388175210\"],\"storedCorrelationIds\":[]}"}
{"timestamp":"2020-08-14T06:56:21.676154801Z","logLevel":"DEBUG","message":"Received event: sh.keptn.event.start-evaluation"}
{"timestamp":"2020-08-14T06:56:21.687093798Z","logLevel":"INFO","message":"Check if event of type sh.keptn.event.start-evaluation should be sent to Dynatrace."}
{"timestamp":"2020-08-14T06:56:21.687203413Z","logLevel":"INFO","message":"Ignoring event."}
{"timestamp":"2020-08-14T06:56:22.275836521Z","logLevel":"DEBUG","message":"Received event: sh.keptn.internal.event.get-sli"}
{"timestamp":"2020-08-14T06:56:22.28325059Z","logLevel":"INFO","message":"Check if event of type sh.keptn.internal.event.get-sli should be sent to Dynatrace."}
{"timestamp":"2020-08-14T06:56:22.283281333Z","logLevel":"INFO","message":"Ignoring event."}
{"timestamp":"2020-08-14T06:57:12.50978067Z","logLevel":"DEBUG","message":"Received event: sh.keptn.event.start-evaluation"}
{"timestamp":"2020-08-14T06:57:12.521350995Z","logLevel":"INFO","message":"Check if event of type sh.keptn.event.start-evaluation should be sent to Dynatrace."}
{"timestamp":"2020-08-14T06:57:12.521398937Z","logLevel":"INFO","message":"Ignoring event."}
{"timestamp":"2020-08-14T06:57:12.929356512Z","logLevel":"DEBUG","message":"Received event: sh.keptn.internal.event.get-sli"}
{"timestamp":"2020-08-14T06:57:12.941623833Z","logLevel":"INFO","message":"Check if event of type sh.keptn.internal.event.get-sli should be sent to Dynatrace."}
{"timestamp":"2020-08-14T06:57:12.941647997Z","logLevel":"INFO","message":"Ignoring event."}

**Comment by marcredhat** [comment] 2020-08-14 18:32
helm-service logs:
{"timestamp":"2020-08-14T18:20:50.712295463Z","logLevel":"INFO","message":"Finished upgrading chart keptnopenshift45-dev-carts in namespace keptnopenshift45-dev"}
{"timestamp":"2020-08-14T18:20:50.712430991Z","logLevel":"DEBUG","message":"Canary action set for service carts in stage dev of project keptnopenshift45 was received"}
{"timestamp":"2020-08-14T18:20:50.712502599Z","logLevel":"DEBUG","message":"Discard canary action set for service carts in stage dev of project keptnopenshift45 because service is not duplicated"}

**Comment by marcredhat** [comment] 2020-08-14 19:33
Also tried https://github.com/keptn/examples/tree/master/simplenodeservice. It gets deployed to -dev just fine and shows up in Dynatrace. However, nothing gets deployed to -staging and -production...

**Comment by marcredhat** [comment] 2020-08-14 20:41
Until we figure out why nothing gets deployed to -staging and -production, I changed my shipyard.yaml as follows:
stages:
  - name: "dev"
    deployment_strategy: "direct"
    #test_strategy: "functional"
    approval_strategy:
      pass: "automatic"
      warning: "automatic"
    deployment_strategy: "blue_green_service"
    test_strategy: "performance"
....

and was able to confirm that Istio injection works fine and that the primary and canary get successfully deployed:
oc get VirtualService
NAME    GATEWAYS                             HOSTS                                                  AGE
carts   [public-gateway.istio-system mesh]   [carts.keptnopenshift45-dev.svc.cluster.local carts]   16h

oc get DestinationRule
NAME            HOST                                                   AGE
carts-canary    carts-canary.keptnopenshift45-dev.svc.cluster.local    8m47s
carts-primary   carts-primary.keptnopenshift45-dev.svc.cluster.local   8m46s

**Comment by agrimmer** [comment] 2020-08-18 11:17
Hi @marcredhat,
thank you for pushing Keptn towards Openshift 4!
From the comments above, I can see that the Bridge is not working and the promotion of an artifact into the next stage is not working. For debugging the problem, I would need the support archive. Can you please generate a new support-archive and send it to me on Slack (@johannes-b is on holiday)?
Thanks, Andreas

**Comment by agrimmer** [comment] 2020-08-19 13:13
Hi @marcredhat,
all errors are caused by the failing MongoDB, which Keptn depends on. 
This is a known issue https://github.com/keptn/keptn/issues/1519

Can you please try out the workaround of running the mongodb in privileged mode, i.e. by executing
`kubectl set image deployment/mongodb mongodb=keptn/mongodb-privileged:latest -n keptn`?

Afterwards, please delete all old projects as they were not correctly created.

**Comment by marcredhat** [comment] 2020-08-19 19:01
Thanks! I had a similar issue with jmeter so I edited the mongo  and jmeter-service deployments as follows:
securityContext:
       runAsUser: 0
Will try 
`kubectl set image deployment/mongodb mongodb=keptn/mongodb-privileged:latest -n keptn` and 
report back

**Comment by marcredhat** [comment] 2020-08-19 19:33
Everything deploys fine in -dev but -staging and -productions remain empty.
Also, evaluations result in "no evaluation performed by lighthouse because no SLI-provider configured for project keptn"

**Comment by johannes-b** [comment] 2020-08-24 10:44
Hi Marc, 
is the MongoDB now running smoothly and do you see projects in the Keptn Bridge? 

To get around the error "_no evaluation performed by lighthouse because no SLI-provider configured for project keptn_", please execute: `keptn configure monitoring dynatrace --project=PROJECTNAME` 
(This creates a ConfigMap that configures Dynatrace as SLI-provider for your project.)

**Comment by marcredhat** [comment] 2020-08-26 03:44
Yes, thanks a lot for your help! I put together an easy automated way to deploy OpenShift 4.5, Service Mesh and Keptn on your laptop or virtual machine: https://github.com/marcredhat/crcdemos/blob/master/keptn.adoc
So I'd suggest using the above to reproduce any further issues, automate OpenShift / Keptn testing for new versions etc

**Comment by johannes-b** [comment] 2020-08-26 13:36
Marc, many thanks for your great work and for pulling everything together into the document! 

Let me bring @jetzlstorfer into this discussion to plan on a Keptn/OpenShift 4.4 tutorial published on: https://tutorials.keptn.sh/
This would help the Keptn project to share your findings.

**Comment by johannes-b** [comment] 2020-09-03 11:54
Hi Marc, 
today I managed to setup Keptn on OpenShift 4.5 according to your docu. The docu is phenomenal!

Just one remark: can you please add the step of adapting the mongodb: 
* `kubectl set image deployment/mongodb mongodb=keptn/mongodb-privileged:latest -n keptn`
* `securityContext: runAsUser: 0`

I had to set `runAsUser` as follows (I removed the fsGroup property):
```
securityContext:
   runAsUser: 1000589999
```

Can you tell me why I had to set it to this value?

**Comment by johannes-b** [comment] 2020-09-04 05:35
I could successfully test Keptn on OpenShift 4.5. Hence, I close this issue. 

Follow-up tasks is an integration test for Travis CI based on this issue: #2285

**Closed by johannes-b** 2020-09-04 05:35 UTC
Labels: platform:openshift
