### ISSUE TITLE
API: Limit the maximum size of incoming events

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#8557] opened 2022-08-02 08:50 UTC
Currently, the `POST api/v1/event` endpoint (implemented in the `api-service`) does not restrict the maximum size of events sent to Keptn. Since information from incoming events is persisted at numerous places, we should limit the maximum size of events to avoid unwanted performance degradations in our APIs. The size restrictions should be in line with the CloudEvents API: 

https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#size-limits

**Comment by thisthat** [comment] 2022-08-02 12:22
Duplicate of https://github.com/keptn/keptn/issues/5544

**Closed by thisthat** 2022-08-02 12:22 UTC
Labels: area:core, ready-for-refinement
