### ISSUE TITLE
Broken helm charts dont lead to any error message

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#831] opened 2019-09-15 12:17 UTC
**Describe the bug**
I updated my helm charts and made a mistake. The problem is that there is no indication that the deployment failed because of the lack of a DEPLOYMENT_FINISHED (status=failed) event that is sent by e.g: Helm Service.
The keptns bridge also only shows the following message:
Error executing command helm upgrade --install simpleproject-staging simpleproject/helm-chart --namespace simpleproject-staging --wait: exit status 1

**To Reproduce**
Break your helm charts and deploy

**Expected behavior**
I am suggesting two things
#1: Provide more detailed error message from Helm Service
#2: Make the deployment tool send a DEPLOYMENT_FINISHED event but with a status failed + detailed status message.

**Comment by agrimmer** [comment] 2019-09-16 05:32
The problem is known and it was fixed by https://github.com/keptn/go-utils/commit/ce53859f72a94b081f9869d0c2d38b850b93d96d#diff-29171ab01ec92e76aa16b114dd686623.

**Closed** 2019-09-16 05:32 UTC
