### ISSUE TITLE
Unable to onboard project if the first attempt using bad upstream repo credentials fails

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#1625] opened 2020-04-08 16:56 UTC
**Environment**

* Client OS (e.g., Linux, OSX, Windows):  Mac
* Keptn Version (`keptn version`): 0.6.1
* Kubernetes Cloud Provider (e.g., GKE, AKS): eks
* Kubernetes version (`kubectl version`): "v1.14.7-eks-1861c5

**Affected Component**

* [ ] Docs
* [X ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

Unable to onboard project if the first attempt using bad upstream repo credentials fails

**To Reproduce**

## 1. make project with bad user ID
mac# keptn create project bitbucket-demo --shipyard=shipyard.yaml --git-user=yyy --git-token=xxx --git-remote-ur
l=https://bitbucket.org/dynatracedemos/keptn-simplenodeservice
Starting to create project
ID of Keptn context: 33503863-1920-438f-b1af-ac370c6b200a
Creating project bitbucket-demo1 failed. Could not commit changes.

## 2.  fix password try again
mac# keptn create project bitbucket-demo --shipyard=shipyard.yaml --git-user=yyy --git-token=xxx --git-remote-url=https://bitbucket.org/dynatracedemos/keptn-simplenodeservice
Starting to create project
ID of Keptn context: 40639a42-1519-47ca-8de1-caba3f8dcf9e
Creating project bitbucket-demo failed. Project already exists

## 3. Now can't delete project
mac# keptn delete project bitbucket-demoStarting to delete project
error when getting shipyard: {"code":404,"message":"Project resource not found"}
.
mac# keptn delete project bitbucket-demo1
Starting to delete project
error when getting shipyard: {"code":404,"message":"Project resource not found"}
.

**Expected behavior**

Should get better error that upstream creds where bad and this should not make a project yet.  If have a project, should be able to call the keptn delete project command and have it work.

**Current behavior**
Unable to delete project. Thus, unable to onboard the app with the project name I want to use.

**Screenshots**

**Additional context**

**Comment by christian-kreuzberger-dtx** [comment] 2020-04-09 07:18
Thanks for the report.

This is a duplicate of (or at least heavily related to) https://github.com/keptn/keptn/issues/1545.

**Closed by christian-kreuzberger-dtx** 2020-04-09 07:18 UTC
