### ISSUE TITLE
Deployment-finished root event does not show image/tag

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1662] opened 2020-04-21 11:52 UTC
When Keptn receives a deployment-finished event as root event, the Bridge does not show image and tag like for a `configuration-change` (see below):

![image](https://user-images.githubusercontent.com/729071/79862978-3fcf9f00-83d7-11ea-9373-476be09ca270.png)

The implementation should consider that also other root events may arrive. Hence, always show `image:tag` when the information is available. 

**Definition of Done**
- [ ] The image and tag are shown when root event contains this information.

**Comment by christian-kreuzberger-dtx** [comment] 2020-04-21 12:21
Is this a duplciate of #1577 (which should already be fixed)?

**Comment by ermin-muratovic** [comment] 2020-04-30 12:57
Yes, this is a duplicate of #1577 and is already fixed.

**Closed by ermin-muratovic** 2020-04-30 12:57 UTC
Labels: area:bridge.2.0, sprint:28, type:bug
