### ISSUE TITLE
swagger ui not working correclty in keptn 0.6b quality gate

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1145] opened 2019-11-21 13:21 UTC
I cant execute API calls through swagger. The generated CURL works perfectly when I copy it and execute manually - but - the execute button in the swagger ui always fails to execute. could have to do the browser not allowing it because of http/https?

**Comment by christian-kreuzberger-dtx** [comment] 2019-11-26 13:06
Duplicate of #1012

**Closed by christian-kreuzberger-dtx** 2019-11-26 13:06 UTC
