### ISSUE TITLE
webhook-service: Failed request of a list of requests results in `result=pass`

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#6557] opened 2022-01-12 07:43 UTC
**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [x] Webhook
### Use Case

As a user, I define a list of requests that need to be called as part of a webhook subscription: 

![image](https://user-images.githubusercontent.com/729071/149084062-a8eb28d4-df12-4eeb-a360-5f9eaca0b2ca.png)

However, the first request is configured wrong. (see screenshot: `webhook.badsite`). This is also reported as an error when executing the request: 

![image](https://user-images.githubusercontent.com/729071/149084305-c678b7f6-8220-4ac0-bb13-4ae534763db9.png)

### Bug

The bug is that the mytask.finished event, which is sent by the webhook-service contains a `result=pass` even though a request failed. Hence, the user still assumes that everything worked fine:

```
{
  "data": {
    "labels": null,
    "mytask-silent": {
      "responses": [
        ""
      ]
    },
    "project": "demo",
    "result": "pass",
    "service": "casdemoapp",
    "stage": "production",
    "status": "succeeded"
  },
  "id": "6058af4b-d682-4903-b00a-e6a7b6b238c4",
  "source": "webhook-service",
  "specversion": "1.0",
  "time": "2022-01-11T14:04:44.752Z",
  "type": "sh.keptn.event.mytask-silent.finished",
  "shkeptncontext": "e93cf888-7bed-4e61-bc96-c572222cc3dc",
  "triggeredid": "8b4ff55c-7b83-4711-8219-28fbb54552f2"
}
```

**Expected behavior**
- Once there is a request that could not be executed, the webhook-service stops calling the other requests and returns a `task.finished` with `result=failed` including a message: "Error when executing the 1. request of the webhook configuration"

**Comment by thisthat** [comment] 2022-01-12 09:02
This occurred in Keptn 0.10. This might be already fixed in newer versions of Keptn.

**Comment by thisthat** [comment] 2022-01-12 13:51
Duplicate of https://github.com/keptn/keptn/issues/5729

**Closed by thisthat** 2022-01-12 13:51 UTC
Labels: type:bug
