### ISSUE TITLE
Polling stops on Sequence page at some point and newly triggered sequences are not being updated in the page

### ISSUE THREAD

**Issue by Gevorgisk** [keptn/keptn#8380] opened 2022-07-11 12:29 UTC
**Environment**

* Client OS (Windows):
* Keptn Version (`0.16.1`):

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
This issue is randomly reproducible, however it is feasible to reproduce if you try the steps described below couple of times. The issue is that the evaluation is triggered via api and at some point the newly triggered sequence does not appear in Sequences page. Looking to the network it was found out that for some reason Polling request stops to be generating therefor the page is not being updated with the newly triggered sequence. 

**To Reproduce**

1. Go to Sequences page
2. Trigger an evaluation via API
3. If the sequence appeared automatically on the page within 30 sec. then either wait until it is finished or abort it
4. repeat step # 2 if step # 3 was actual, otherwise it means you have reproduced the issue.

**Expected behavior**
Every newly triggered sequence should be updated in the page withing 30 sec

**Current behavior**
Sometimes newly triggered sequence appears automatically on Sequences page and sometimes not.

**Screenshots**
![image](https://user-images.githubusercontent.com/14317365/178264120-c864c57e-2bd9-4945-b63d-770d57a9fddb.png)

**Additional context**

**Comment by Kirdock** [comment] 2022-07-11 13:49
My guess is that the polling did not stop but instead the update was lost. The root cause may be parallel requests, which happened in 0.16.x and were fixed in 0.17. I can't reproduce it in 0.17. I could reproduce it once in 0.16.x and here the polling was still in place but somehow the update was lost. Could you check if this still happens in 0.17?

**Comment by Gevorgisk** [comment] 2022-07-11 14:19
Of course I can verify it once I have/get a deployment of 0.17.

**Closed** 2022-10-24 06:46 UTC
Labels: type:bug, bridge.2.0, on hold
