### ISSUE TITLE
Approvals are not working

### ISSUE THREAD

**Issue by thschue** [keptn/keptn#3477] opened 2021-03-09 13:46 UTC
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, macOS, Windows):
* Keptn Version (`keptn version`): 0.8.0
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [x] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

When defining a manual approval step and declining the approval, the following tasks will be triggered

**To Reproduce**

* Define a shipyard with a manual approval and tasks afterwards
* Trigger a deployment
* Decline the approval in the bridge

**Expected behavior**

The workflow is stopped

**Current behavior**

The workflow continues

**Screenshots**

![image](https://user-images.githubusercontent.com/38893055/110479842-2108f280-80e6-11eb-9b47-405379cf38aa.png)

**Comment by christian-kreuzberger-dtx** [comment] 2021-03-09 16:31
Could you please share the `shipyard.yaml` used?

Also, please share the content of the `approval.finished` cloudevent.

**Comment by johannes-b** [comment] 2021-03-09 16:54
In further investigating this issue, @thschue and I could narrow down the problem to the Bridge since the use-case worked with the CLI. 

The used Shipyard is:
```
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "platform-integration"
spec:
  stages:
    - name: "integration"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
            - name: approval
              properties: 
                pass: manual
                warning: manual          
            - name: "echo"
            - name: "evaluation"
```

**Issue:** Even though @thschue pushed the X button in the Bridge to decline the approval, the Bridge sent an event with `result: pass`. (see the above screenshot)

**Comment by ermin-muratovic** [comment] 2021-03-10 08:25
@johannes-b as Christian requested, maybe you can provide us the content (payload) of the `approval.finished` cloudevent?

Andreas already reported the same behaviour in #3366 and it should have been fixed with #3379

**Comment by johannes-b** [comment] 2021-03-10 09:26
@thschue will reproduce the problem and then I can provide the payload.

**Comment by Kirdock** [comment] 2021-03-15 13:32
payload: 
```json
{
  "data": {
    "approval": {
      "result": "fail",
      "status": "succeeded"
    },
    "configurationChange": {
      "values": {
        "image": "docker.io/keptnexamples/carts:0.12.3"
      }
    },
    "deployment": {
      "deploymentNames": [
        "direct",
        "canary"
      ],
      "deploymentURIsLocal": [
        "http://carts.sockshop-approve-dev:80",
        "http://carts.sockshop-approve-staging:80"
      ],
      "deploymentURIsPublic": [
        "http://carts.sockshop-approve-dev.34.72.118.255.nip.io:80",
        "http://carts.sockshop-approve-staging.34.72.118.255.nip.io:80"
      ],
      "deploymentstrategy": "direct",
      "gitCommit": "e5a78ebb145a7f8ea8d2428383232db2ff580117"
    },
    "evaluation": {
      "gitCommit": "",
      "indicatorResults": null,
      "result": "no evaluation performed by lighthouse because no SLI-provider configured for project sockshop-approve",
      "score": 0,
      "sloFileContent": "",
      "timeEnd": "2021-03-10T11:14:20Z",
      "timeStart": "2021-03-10T11:13:59Z"
    },
    "message": "",
    "project": "sockshop-approve",
    "release": {
      "gitCommit": ""
    },
    "result": "",
    "service": "carts",
    "stage": "production",
    "status": "",
    "test": {
      "end": "2021-03-10T11:14:20Z",
      "gitCommit": "",
      "start": "2021-03-10T11:13:59Z"
    }
  },
  "id": "fcb30d2c-3010-4ba5-98eb-c82760938b40",
  "source": "https://github.com/keptn/keptn/bridge#approval.finished",
  "specversion": "1.0",
  "time": "2021-03-15T12:39:51.202Z",
  "type": "sh.keptn.event.approval.finished",
  "shkeptncontext": "48d7a79a-1f42-415f-a753-c9c5ff50ff2c",
  "triggeredid": "d3b2c1cb-e491-479d-9a85-29ed19954acb"
}
```

**Closed** 2021-03-16 08:23 UTC
Labels: bridge.2.0, type:bug
