### ISSUE TITLE
Prevent collision of two new-artifact events of the same service

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1219] opened 2019-12-09 19:02 UTC
When sending a new artifact event for a service that is currently deploying a new artifact in that same stage keptn should come up with a better mechanism to avoid these two deployments to impact each other. Here two suggestions
#1: Queue a new Artifact Event if the current stage is "in progress"
#2: Stop current execution and give priority to new artifact

**Comment by agrimmer** [comment] 2020-07-10 08:47
Duplicate of https://github.com/keptn/keptn/issues/360

**Closed by agrimmer** 2020-07-10 08:47 UTC
Labels: area:workflow-engine, future
