### ISSUE TITLE
Keptn 0.8.3 shows that it uses specversion 0.2.1 instead of 0.2.2

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4192] opened 2021-05-28 08:38 UTC
In Keptn 0.8.3, CloudEvents contain the field `shkeptnspecversion` which apparently is set to 0.2.1.

This is in contrast to the actually used CloudEvents of Spec 0.2.2 (see [release notes](https://github.com/keptn/keptn/releases/tag/0.8.3)).

# Actions

- Find out why Keptn 0.8.3 says that Spec 0.2.1 is used instead of 0.2.2 and document the root-cause in this issue
- Verify if our [release process](https://github.com/keptn/keptn/wiki/Release-Checklist) needs to be adapted

**Comment by bacherfl** [comment] 2021-05-31 13:48
Investigations showed that this was caused by an accidental modification of the `specification` submodule after PR #4128 had been merged.
As discussed in an internal meeting, we have to be aware of changes made to the submodule and not accept any PRs that change it without clearly stating the intention to do so in the PR description/title

**Closed by bacherfl** 2021-05-31 13:48 UTC
Labels: area:core, ready-for-refinement, type:bug
