### ISSUE TITLE
After upgrade Sequences are gone and Service view stucks in "Loading..."

### ISSUE THREAD

**Issue by melcsanad** [keptn/keptn#6646] opened 2022-01-20 23:09 UTC
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Red Hat Enterprise Linux release 8.5 (Ootpa)
* Keptn Version (`keptn version`): 0.12.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): Local installation of Kubernetes
* Kubernetes version (`kubectl version`) :v1.18.15

Browser Chrome: Version 85.0.4183.83 (Official Build) (32-bit)

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

After upgrade to Keptn version 0.10.0 the historical sequenses are not visible in sequence view and stuck in "Loading.." in Service screen if click on any Services. Only new sequences are visible. Update to 0.11.x and later to 0.12.0 didn't solve the problem.

**To Reproduce**

Open sequences of any project.

**Expected behavior**

show evaluations on Service screen.
show historical sequences on servcei screen.

**Current behavior**

historical sequenses are not visible in sequence view and stuck in "Loading.." in Service screen if click on any Services

**Screenshots**

![missing seq](https://user-images.githubusercontent.com/98130057/150436372-91b82e00-5e8b-4ce9-99b1-36eda72f9de4.png)
![missing evaluation](https://user-images.githubusercontent.com/98130057/150436385-3787eb57-01d4-4c0f-a023-e9d02b884b3e.png)

**Additional context**

**Comment by bacherfl** [comment] 2022-01-21 11:10
HI @melcsanad 

Which version of Keptn did you use previously before upgrading to 0.10.0? Also, If possible, may I ask you to try to install 0.10.0 again and gather the logs of the `shipyard-controller`, using the following command:

```
kubectl logs -n keptn svc/shipyard-controller -c shipyard-controller
```

Hopefully this will provide us with some additional information to solve this problem

**Comment by melcsanad** [comment] 2022-01-21 12:25
Hi @bacherfl ,
I upgraded from 0.9.2.  I try to restore I do t again. I let you inform about the result (with the logs too)

**Comment by melcsanad** [comment] 2022-01-26 16:29
Hi @bacherfl,
I have restored to 0.8.7 and repeated the upgrade to 0.9.0 because I've already lost these function there. Have some changes in helm suggested by @johannes-b during upgrade troubleshoting:
- change the mongodb mem size to 500MB
- remove the lines 45 – 50. (readynessProbe) from file mongodb-datastore.yaml 

Log attached
[shipyard-controller.log](https://github.com/keptn/keptn/files/7943355/shipyard-controller.log)
Have supportArchive too, if you would need it.

**Comment by bacherfl** [comment] 2022-01-27 09:39
Hi @melcsanad, thank you for the update! Are the sequences that were lost after the upgrade to 0.10.0 now visible again with 0.9.0? If yes, can you please post some examples of the root events that triggered these sequences? (i.e. the payload of the first triggered event of the respective sequence)?

**Comment by bacherfl** [comment] 2022-01-31 08:09
Hi @melcsanad, thank you for the additional information - I think the problem here is that the evaluations were previously triggered by sending a `sh.keptn.event.evaluation.triggered`, instead of a `sh.keptn.event.<stage-name>.evaluation.triggered` event - The first one directly triggers the evaluation *task*. performed by the lighthouse-service, while the latter triggers a *sequence*. containing the evaluation task.
In 9.0 we migrated to a new API for retrieving the list of sequences, which is automatically migrated using the event traces for sequences started with a `sh.keptn.event.<stage-name>.<sequence-name>.triggered` event, so that explains why the previous executions of the evaluation task are not included in the list anymore. We will discuss internally on how to best address this problem and will keep you updated

**Comment by thisthat** [comment] 2022-02-01 12:10
Hi @melcsanad, this is -unfortunately- working as intended. Previously, the Bridge sequence screen was showing also elements that were not sequences. In Keptn 0.9.0, we fixed the problem. I will close the issue, but I am interested to understand your use case to see the old evaluations in the sequence screen and not only on the heatmap page.

**Closed by thisthat** 2022-02-01 12:10 UTC
Labels: type:bug
