### ISSUE TITLE
Add URL links within Keptn Bridge to Keptn Docs and Keptn Swagger UI

### ISSUE THREAD

**Issue by robertjahn** [keptn/keptn#1503] opened 2020-03-16 12:11 UTC
**Is your feature request related to a problem? Please describe.**
This would allow for quick reference for aa bridge user

**Describe the solution you'd like**
1. have url back to the keptn docs (for the keptn version using)
1. have url to swagger UI
You could have a few simple links for now, but thinking ahead as bridge grows you might want to make aa drop down menu off the keptn top left icon.  The drop down could have things like preferences, logout, info about keptn & bridge version/setup, and these links. 

**Describe alternatives you've considered**
None

**Additional context**
If like the menu idea, just look to other tools.  The usually have a collapsable menu with icons when small and text when big.  Just one example:
![image](https://user-images.githubusercontent.com/24907089/76757144-79204980-675d-11ea-8090-2b8129e2f7a3.png)

**Comment by agrimmer** [comment] 2020-07-10 09:14
Closing this issue as it is a duplicate of https://github.com/keptn/keptn/issues/1635

**Closed by agrimmer** 2020-07-10 09:14 UTC
Labels: area:bridge.2.0
