### ISSUE TITLE
Common base image for all Go-based Keptn Core Services

### ISSUE THREAD

**Issue by mowies** [keptn/keptn#7395] opened 2022-04-07 09:38 UTC
We have very similar Dockerfiles, base images, dependencies and other common things duplicated in every service.

We could create a common base image for our core services which comes with everything needed for the services.

**Comment by thisthat** [comment] 2022-04-20 06:20
Duplicate of https://github.com/keptn/keptn/issues/6802

**Closed** 2022-04-20 10:59 UTC
Labels: area:core, ready-for-refinement
