### ISSUE TITLE
DELETE /project/{project}/service/{service} endpoint fails with 504: the service folder deleted in upstream but left in UI

### ISSUE THREAD

**Issue by Gevorgisk** [keptn/keptn#7481] opened 2022-04-14 12:52 UTC
* Client OS (Windows):
* Keptn Version (0.12.6):
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [x] REST API
* [ ] Webhook

**Describe the bug**
When DELETE "https://<tenant-base-url>/api/controlPlane/v1/project/<prj-name>/service/<service-name>" fails with 504 "gateway timeout" error 
then the service folder is being removed from the upstream and the service is left in Keptn UI. And furthermore the user is not able to do anymore actions with the service. 
When you try to delete the service again then it says:
{
  "code": 500,
  "message": "could not delete service <service-name> from stage <stage-name>: Service does not exists"
}

The only way that I found to delete the service is to manually create the service folder in the upstream and then it was possible to delete that.

**To Reproduce**
To reproduce the issue you should execute the endpoint "/project/{project}/service/{service}" so that it fails with "504 gateway timeout error". Then you should see that the service is broken anymore, which means no more evaluation can be triggered successfully against that service or the service cannot be deleted anymore via api.

**Expected behavior**

If the request is failing the related folder of the service should not be deleted in the upstream.

**Current behavior**

**Screenshots**

**Additional context**

**Comment by thisthat** [comment] 2022-04-15 05:26
Duplicate of #7446

**Closed by thisthat** 2022-04-15 05:26 UTC
Labels: type:bug

**Comment by carpe-github** [comment] 2022-04-15 08:53
@thisthat, tbh, I do not think this is a duplicate of #7446.
Why I do think so? because the issue that I reported in this ticket describes the flow which leads to the state where the issue of   #7446 is visible.
To describe it in more constructive way:
1. When DELETE /project/{project}/service/{service} endpoint fails with 504 gateway error then it happens so that the service related folder is being removed in the upstream but the service still continues to stay in keptn (ui).
And after that you get a state when the service cannot be deleted anymore from the system which is described in #7446.

That's why the issue of #7481 is different, the expected result here should be the case that if the request is failing then the upstream data should not be removed just simply because the service stays in keptn ui.

Expecting to re-open this ticket. Thanks!

**Comment by Gevorgisk** [comment] 2022-04-15 08:55
@thisthat, tbh, I do not think this is a duplicate of https://github.com/keptn/keptn/issues/7446.
Why I do think so? because the issue that I reported in this ticket describes the flow which leads to the state where the issue of https://github.com/keptn/keptn/issues/7446 is visible.
To describe it in more constructive way:
When DELETE /project/{project}/service/{service} endpoint fails with 504 gateway error then it happens so that the service related folder is being removed in the upstream but the service still continues to stay in keptn (ui).
And after that you get a state when the service cannot be deleted anymore from the system which is described in https://github.com/keptn/keptn/issues/7446.

That's why the issue of https://github.com/keptn/keptn/issues/7481 is different, the expected result here should be the case that if the request is failing then the upstream data should not be removed just simply because the service stays in keptn ui.

Expecting to re-open this ticket. Thanks!

**Comment by thisthat** [comment] 2022-04-15 09:21
@Gevorgisk thank you for the explanation, I now agree to don't mark this as a duplicate but rather as "dual-problem" of #7446. 

If a call to delete a service fails with a 504 error, I believe Keptn should not try to revert the deletion of the service in the upstream. 
My motivations are:
- Keptn does multiple actions to fulfill the deletion requests and it doesn't know the timeout configured in Nginx that triggers the 504. Therefore it doesn't know exactly which action to revert.
- If the upstream deletion took longer, trying to revert it would also most likely result in a 504. 

I would suggest that the implementation of #7446 is more robust in handling this problem: if something goes wrong while deleting a service, calling again the same delete API would not fail and always try to delete everything. Hence, we foster in the caller to use a retry-logic if something goes wrong. 

Would you agree @Gevorgisk or do you have a different opinion?

**Comment by Gevorgisk** [comment] 2022-04-15 09:46
Looking to the issue from black-box perspective my opinion still continues to be the same, which is about to not delete anything what was supposed to be deleted if the request is failing, and I think this is true generally for any type of application.

From white-box perspective, since I am not very in deep into implementation details, here my advice would me first to check that the service is deleted from keptn (db or wherever it is recorded), and after that try to delete the related data from the upstream. 
--my 2 cents.

**Comment by thisthat** [comment] 2022-04-19 11:28
Generally speaking, I agree with you. However, looking at the future of Keptn, we could move to use external services to handle the configuration (e.g., s3 bucket) and here, we won't have any control, nor the certainty that a revert procedure is possible. [KEP70]( https://github.com/keptn/enhancement-proposals/pull/70#issuecomment-1094960064) has some discussion on this theme going on.
