### ISSUE TITLE
Keptn on microk8s 

### ISSUE THREAD

**Issue by sachgit30** [keptn/keptn#1886] opened 2020-06-06 06:33 UTC
I am trying keptn v0.6.2 on microk8s cluster. I installed keptn v0.6.2 with quality gates option on microk8s and also able to authenticate keptn cli with k8s cluster. But receive error while creating Keptn project
$ keptn create project mystatements --shipyard=shipyard-quality-gates.yaml
Starting to create project
**Create project was unsuccessful
Error: Create project was unsuccessful. Post http://event-broker.keptn.svc.cluster.local: dial tcp: lookup event-broker.keptn.svc.cluster.local: Try again**
I even see eventbroker-go pod running on cluster with no issues.
Please can you help with this error

**Comment by agrimmer** [comment] 2020-06-08 08:28
I am closing this issue because it was caused by a networking issue of the VM.

**Closed by agrimmer** 2020-06-08 08:28 UTC
