### ISSUE TITLE
keptn leaves canary deployment and pod running

### ISSUE THREAD

**Issue by cjmckenna** [keptn/keptn#1870] opened 2020-06-03 19:30 UTC
**Environment**

* Client OS: Linux
* Keptn Version: 0.6.2
* Kubernetes Cloud Provider: NONE
* Kubernetes version: Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Affected Component**

* [ ] Docs
* [X] CLI
* [X] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
When deploying via keptn using the keptn send event cli command, keptn properly creates the canary and primary deployments and pods but contrary to the documentation here:https://keptn.sh/docs/0.6.0/reference/helm/

the canary pod and deployment never gets scaled down after the completion of the quality gates tests

**To Reproduce**

### Create Project and Service

keptn create project full-demo --shipyard=shipyard.yaml

keptn onboard service full-demo-service --project=full-demo --chart=./charts

### Upload resources and activate SLI:

keptn add-resource --project=full-demo --stage=dev --service=full-demo-service --resource=jmeter/basiccheck_dev.jmx --resourceUri=jmeter/basiccheck.jmx

keptn add-resource --project=full-demo --stage=pvs --service=full-demo-service --resource=jmeter/load_pvs.jmx --resourceUri=jmeter/load.jmx

keptn add-resource --project=full-demo --stage=pvs --service=full-demo-service --resource=slo.yaml --resourceUri=slo.yaml

keptn add-resource --project=full-demo --stage=pvs --service=full-demo-service --resource=sli-config.yaml --resourceUri=dynatrace/sli.yaml

keptn configure monitoring dynatrace --project=full-demo --suppress-websocket

keptn send event new-artifact --project=full-demo --service=full-demo-service --image=docker.io/cjmckenna/full-demo-service --tag=0.0.1

**Expected behavior**

It is expected that after the completion of the functional and performance tests and subsequent promotions, that the canary deployment and pods would be scaled down as per the following documentation:
https://keptn.sh/docs/0.6.0/reference/helm/

**Current behavior**
keptn is leaving the canary deployment and pods running and it also appears that traffic is still routed to the canary even after promotion

<img width="1419" alt="Screen Shot 2020-06-03 at 3 29 13 PM" src="https://user-images.githubusercontent.com/28633200/83680549-1b0e4000-a5af-11ea-8439-5df47ea5bb03.png">

**Comment by johannes-b** [comment] 2020-06-04 05:58
Hi, 

the behavior you are describing is not the desired one since the canary deployment/pods should be scaled down as documented in keptn/docs. 

The steps you explained for reproducing the scenario are very detailed. However, it is difficult to tell the actual behavior without taking a look into the logs. May I ask you to retrieve the logs of the helm-service. For doing so you can use the command: `keptn generate support-archive`  [command details](https://keptn.sh/docs/0.6.0/reference/cli/commands/keptn_generate_support-archive/)

(Or you can run: `kubectl logs helm-service-579f8cbdbf-r2ffw -n keptn` ) 

Feel free to post the logs here or on Slack so that we can investigate your problem.

**Comment by agrimmer** [comment] 2020-06-04 06:21
Hi @ cjmckenna,
thank you for your description!
When I investigated your behavior, I noticed that we had a bug in our docu, which I fixed with https://github.com/keptn/keptn.github.io/pull/557.
More precisely, the descriptions in https://keptn.sh/docs/0.6.0/manage/service/#onboard-your-own-service were missing an important requirement for the Helm chart:
The values file has to contain a `replicaCount` property, which has to be used in the deployment.
If this `replicaCount` is not used in the deployment, Keptn cannot do the downscaling.

May I ask you to double-check your Helm-chart according to https://keptn.sh/docs/0.6.0/manage/service/#onboard-your-own-service?
You can correct the values and deployment file in your GIT repo.

Please let us know if this solves your issue.
Thanks, Andreas

**Comment by christian-kreuzberger-dtx** [comment] 2020-06-04 11:21
I can confirm that not having `replicaCount` as a variable will cause the issue that the canary deployment is not scaled down.

What I am still puzzled about is the last sentence you wrote:

> ... and **it also appears that traffic is still routed to the canary even after promotion**

Please note that after successful promotion to the next stage it might take until the primary deployment is the one that is getting the traffic (though we're talking seconds to minutes here). Please let us know if this problem persists.

**Comment by cjmckenna** [comment] 2020-06-04 13:18
I will make these changes and will report back on my results.

I am very curious though….. what will happen if the replica count is MORE than 1.  In many of our deployments we create 5 replicas for load balancing and resiliency.  Will keptn react properly to a higher replica count?

**Comment by agrimmer** [comment] 2020-06-04 14:56
Thank you @cjmckenna!
Yes, Keptn can also handle replica counts greater than 1.

**Closed** 2020-06-05 13:32 UTC
Labels: type:bug
