### ISSUE TITLE
Git set upstream without `Git user` does not work

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7496] opened 2022-04-15 08:19 UTC
**Environment**

* Keptn Version (`keptn version`): `0.14.1`

**Affected Component**

* [x] Bridge

**Describe the bug**

* When trying to set an upstream without `Git user` (since it is not required anymore), the **Set Git upstream** button does not work. Please see the network trace that stays empty: 
![image](https://user-images.githubusercontent.com/729071/163544599-7f9896c8-ee5c-434e-b144-d43a0c15ee67.png)

**To Reproduce**

* Create a project without upstream repo
* Follow the link: 
![image](https://user-images.githubusercontent.com/729071/163544964-54333324-0fc5-4dc9-8b9e-344fe5ba20bc.png)
* Enter `Git URL` and `Git Token`
* Click **Set Git upstream** button

**Expected behavior**

* Since the `Git user` is not mandatory anymore, I would expect that setting upstream without user works. 

**Current behavior**

When providing the `Git user`, the operation works: 
![image](https://user-images.githubusercontent.com/729071/163544078-cdd14ff0-7492-496e-8f3d-0b9f16de34eb.png)

**Comment by thisthat** [comment] 2022-04-19 04:48
Duplicate of #7186 and fixed by #7330

**Comment by johannes-b** [comment] 2022-04-19 06:48
I tried to verify the bug fix with `docker.io/keptndev/bridge2:0.15.0-dev-PR-7330.20220413063`, but it is not resolved there. 

As mentioned above, when entering just a `token` without `user`, the **Set Git upstream** button does not work.

**Closed** 2022-04-22 06:48 UTC
Labels: type:bug, area:core, bridge.2.0
