### ISSUE TITLE
keptn Release Notes 0.1: link to getting started section leads to page not found!

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#13] opened 2019-02-18 09:40 UTC
**Describe the bug**
Broken link in release notes

**To Reproduce**
1. Go to https://github.com/keptn/keptn/releases
2. Click on 'getting started section'
3. See error

**Comment by jetzlstorfer** [comment] 2019-02-18 11:42
Thanks for pointing this out!
The issue is now fixed.

**Closed by jetzlstorfer** 2019-02-18 11:42 UTC
