### ISSUE TITLE
Send data of subscribed Keptn-services (via distributors) to uniform

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4031] opened 2021-05-11 09:20 UTC
As a user, I want to see which Keptn-services/integrations (regardless of where they run, e.g., control-plane vs. execution-plane) have subscribed to certain events and whether they are currently connected or have recently received/sent cloudevents. 
Therefore, the Keptn-service/integration needs to register at uniform (located in Keptn control-plane, e.g., shipyard-controller) and provide some metadata (service name, hostname, cloudevent types).

## Pain

Currently, our control-plane does not know which Keptn-services are connected and what events they subscribe to. It is unknown to the end-user (and to Keptn), whether any service reacts on a certain event type (e.g., `deployment.triggered`), and if it does, which one it is and whether it is healthy (= has recently processed any cloudevents).

## Details

Keptn-services (integrations) are usually started on Kubernetes and have a distributor as a sidecar. The service itself does not know about the sidecar, though it communicates with it via some REST API Endpoints (that are basically forwarded to Keptn control-plane).

When starting up, the distributor should register with the Keptn control-plane and provide the following details:

* which event types is the Keptn-service subscribed to (e.g., `sh.keptn.event.>` or `sh.keptn.event.deployment.triggered`)
* which project, service, and stage filters are active/inactive
* distributor version
* kubernetes metadata like namespace, pod name, deployment name (might need to be passed as environment variables to the distributor)
* additional metadata (e.g., hostname, deployment name, service name, service version) 

In addition, when (gracefully) stopping, distributor should unregister with the Keptn control-plane. Please send the same parameters as with the register endpoint, so we can map the request.

*Note*: If the service crashes or anything bad happens, we will not always know. But it's good to know if and when it was gracefully stopped.

## Assumptions

- API endpoints in shipyard-controller for registering and unregistering already exist (see https://github.com/keptn/keptn/issues/4041 )

## Actions

- Extend distributor to register via the API endpoint of shipyard-controller on startup
- Extend distributor to unregister via the API endpoint of shipyard-controller on graceful exit (e.g., SIGKILL, SIGTERM)

## Definition of Done

- [ ] Distributor registers when starting up and the information is available in shipyard-controller

## Dependencies

- https://github.com/keptn/keptn/issues/4041

**Comment by warber** [comment] 2021-05-18 11:56
Duplicate of #4041

**Closed** 2021-06-14 12:58 UTC
Labels: area:core, estimate: 3, kep:45, story
