### ISSUE TITLE
Bridge: task subscriptions UI does not provide a way to re-create a subscription for all events

### ISSUE THREAD

**Issue by arthurpitman** [keptn/keptn#6627] opened 2022-01-19 10:36 UTC
**Environment**
* Keptn Version (`keptn version`): 0.12.0

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
If a user deletes the "wildcard" subscription for an integration, the Bridge does not provide a way to re-create it.

**To Reproduce**

1. Install an integration, such as the dynatrace-service
2. Observe that by default it includes a subscription to all events for all projects, stages and services:
  ![dynatrace-service-all-subscriptions](https://user-images.githubusercontent.com/2436759/150116533-1f24b5d5-b128-4586-b5d5-09fd91d97e3b.png)
3. Remove the wildcard subscription, it now will have no subscriptions:
  ![dynatrace-service-no-subscriptions](https://user-images.githubusercontent.com/2436759/150116622-23583a66-109a-4d4b-a067-7feeb168b1d2.png)
4. Try to recreate the wildcard subscription; it is not possible:
  ![dynatrace-service-cant-recreate-wildcard-subscription](https://user-images.githubusercontent.com/2436759/150116721-1ce1c852-42b0-4400-9e5b-65b3b0e15044.png)

**Expected behavior**
It should be possible to recreate the wildcard subscription in the Bridge UI.

**Current behavior**
It is not possible to recreate the wildcard subscription in the Bridge UI.

**Comment by thisthat** [comment] 2022-01-19 14:16
Hi @arthurpitman, thank your feedback. This works as intended. The motivation is that by using `*`, a user won't know which events the integration will receive. This might cause the integration to fail because it receives events that it cannot parse. However, integrations can specify the wildcard `*` via `PUBSUB_TOPIC` since it knows that it can handle all events. This is the reason why we discourage users to set a wildcard in the Bridge UI.

**Comment by arthurpitman** [comment] 2022-01-20 08:33
Hi @thisthat, that is a really good point.

My motivation is that the user should be able to undo any change they made to the subscriptions. Currently, if a service is set up to receive all events and a user changes this, this is not possible.

An alternate solution would be to allow the user to revert the subscriptions to the integration's defaults.

**Comment by thisthat** [comment] 2022-02-04 11:44
Hi @arthurpitman, we decided that this issue will be addressed in the KEP which we are currently discussing here: https://github.com/keptn/keptn/discussions/6748
More precisely, the last point will provide a way for users to subscribe to custom events so that they can enter `sh.keptn.*` back.
I will close this issue with a "won't fix" and please, follow the discussion and provide your input on that subject :)

**Closed by thisthat** 2022-02-04 11:44 UTC
Labels: type:bug
