### ISSUE TITLE
go-sdk: ResourcesV1() Interface ResourcesV1Interface contains only deprecated functions, no GetResource

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#8722] opened 2022-08-23 11:30 UTC
We were trying to implement an eventhandler that would fetch files using go-sdk, e.g.:
```golang
func (g *GreetingsHandler) Execute(k sdk.IKeptn, event sdk.KeptnEvent) (interface{}, *sdk.Error) {
	greetingsTriggeredData := &GreetingTriggeredData{}
	if err := v0_2_0.Decode(event.Data, greetingsTriggeredData); err != nil {
		return nil, &sdk.Error{Err: err, StatusType: v0_2_0.StatusErrored, ResultType: v0_2_0.ResultFailed, Message: "Could not decode input event data"}
	}

	k.APIV1().ResourcesV1().GetServiceResource(greetingsTriggeredData.Project, greetingsTriggeredData.Service, greetingsTriggeredData.Stage, "my-file.txt")
```

but noticed that literally everything within `k.APIV1().ResourcesV1()` is deprecated:
![image](https://user-images.githubusercontent.com/56065213/186146374-27a5a003-58fc-4827-a225-1ca46fc230b1.png)
https://github.com/keptn/go-utils/blob/65503489d75aac53e74e089babc7a5258887d93c/pkg/api/utils/resourceUtils.go#L22-L88

We then noticed that there is also
```
k.GetResourceHandler()
```

which contains a nice `GetResource` function, which takes a scope, e.g.:
```
	k.GetResourceHandler().GetResource(
		api.ResourceScope{
			project: greetingsTriggeredData.Project,
			greetingsTriggeredData.Service,
			greetingsTriggeredData.Stage,
			"my-file.txt"}
		)
```

However, `k.GetResourceHandler()` returns an unauthenticated resource handler, which doesn't work in remote execution plane, while `k.APIv1().ResourceHandler()` is authenticated (this is fixed by @TannerGabriel in PR https://github.com/keptn/go-utils/pull/534 ).

# Proposal

* Get Rid of `k.GetResourceHandler()` 
* Modify `k.APIv1().ResourceHandler()` to return something that contains `GetResource` function

**Comment by thisthat** [comment] 2022-08-23 11:50
Most likely the problem is here: https://github.com/keptn/go-utils/blob/master/pkg/sdk/internal/api/initializer.go#L76
Where the SDK wires the v1 of the API version instead of [v2](https://github.com/keptn/go-utils/blob/master/pkg/api/utils/v2/client.go)

**Comment by thisthat** [comment] 2022-08-23 12:50
Since it is not clear that the SDK does not provide authenticated methods to access the resource APIs, we should provide a check for http/nats at line: https://github.com/keptn/go-utils/blob/master/pkg/sdk/internal/api/initializer.go#L103 like we do here https://github.com/keptn/go-utils/blob/master/pkg/sdk/internal/api/initializer.go#L62

A resource to have a blueprint implementation could be the k8s-client library where they solved a similar problem

**Comment by odubajDT** [comment] 2022-08-31 07:09
closed via https://github.com/keptn/go-utils/pull/535

**Closed by odubajDT** 2022-08-31 07:09 UTC
Labels: type:bug, area:core, area:go-utils
