### ISSUE TITLE
keptn configure monitoring freezes

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#1466] opened 2020-03-09 21:19 UTC
**Environment**

* Client OS (e.g., Linux, OSX, Windows): mac osx
* Keptn Version (`keptn version`): 0.6.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): gke
* Kubernetes version (`kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**Affected Component**

* [ ] Docs
* [x] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
When executing `keptn configure monitoring dynatrace` right after installation, the CLI freezes and doesn't provide any output to the user. I assume this is due to the fact that the needed secret is missing. However, no output is created for the user to give a hint why the CLI stalls at this point.

**To Reproduce**
1. Install Keptn on a new cluster
2. Execute `keptn configure monitoring dynatrace`

**Expected behavior**
Error message why the command can not be executed.

**Current behavior**
CLI freezes/stalls.

**Screenshots**

![image](https://user-images.githubusercontent.com/7677092/76258517-1c3b0580-622a-11ea-84e9-03831c516c71.png)
Stalls at this point.

**Additional context**

![image](https://user-images.githubusercontent.com/7677092/76258455-f9a8ec80-6229-11ea-9629-47c7e24b4c42.png)
In this context, also the monitoring source/type naming is not consistent. Not sure which is the correct wording.

**Comment by christian-kreuzberger-dtx** [comment] 2020-03-10 07:00
Duplicate of  #1464.

**Closed by christian-kreuzberger-dtx** 2020-03-10 07:00 UTC
